import { CharacterExitNihilo } from "@actor/character";
import { ActorType } from "@actor/data";
import { ArmorExitNihilo } from "@item/armor/document";
import { ConditionExitNihilo } from "@item/condition/document";
import { ContainerExitNihilo } from "@item/container/document";
import { EquipmentExitNihilo } from "@item/equipment/document";
import { WeaponExitNihilo } from "@item/weapon/document";
import { JournalSheetExitNihilo } from "@module/journal-entry/sheet";
import { actionTraits, armorTraits, consumableTraits, creatureTraits, equipmentTraits, weaponTraits } from "./traits";

export type StatusEffectIconTheme = "default" | "blackWhite";

const actorTypes: Record<ActorType, string> = {
    character: "ACTOR.TypeCharacter",
    npc: "ACTOR.TypeNpc",
};

/** Non-detection- and attitude- related conditions added to the Token HUD */
const tokenHUDConditions = {
    blinded: "EXITNIHILO.ConditionTypeBlinded",
    broken: "EXITNIHILO.ConditionTypeBroken",
    clumsy: "EXITNIHILO.ConditionTypeClumsy",
    concealed: "EXITNIHILO.ConditionTypeConcealed",
    confused: "EXITNIHILO.ConditionTypeConfused",
    controlled: "EXITNIHILO.ConditionTypeControlled",
    dazzled: "EXITNIHILO.ConditionTypeDazzled",
    deafened: "EXITNIHILO.ConditionTypeDeafened",
    doomed: "EXITNIHILO.ConditionTypeDoomed",
    drained: "EXITNIHILO.ConditionTypeDrained",
    dying: "EXITNIHILO.ConditionTypeDying",
    encumbered: "EXITNIHILO.ConditionTypeEncumbered",
    enfeebled: "EXITNIHILO.ConditionTypeEnfeebled",
    fascinated: "EXITNIHILO.ConditionTypeFascinated",
    fatigued: "EXITNIHILO.ConditionTypeFatigued",
    "flat-footed": "EXITNIHILO.ConditionTypeFlatFooted",
    fleeing: "EXITNIHILO.ConditionTypeFleeing",
    frightened: "EXITNIHILO.ConditionTypeFrightened",
    grabbed: "EXITNIHILO.ConditionTypeGrabbed",
    immobilized: "EXITNIHILO.ConditionTypeImmobilized",
    invisible: "EXITNIHILO.ConditionTypeInvisible",
    paralyzed: "EXITNIHILO.ConditionTypeParalyzed",
    "persistent-damage": "EXITNIHILO.ConditionTypePersistent",
    petrified: "EXITNIHILO.ConditionTypePetrified",
    prone: "EXITNIHILO.ConditionTypeProne",
    quickened: "EXITNIHILO.ConditionTypeQuickened",
    restrained: "EXITNIHILO.ConditionTypeRestrained",
    sickened: "EXITNIHILO.ConditionTypeSickened",
    slowed: "EXITNIHILO.ConditionTypeSlowed",
    stunned: "EXITNIHILO.ConditionTypeStunned",
    stupefied: "EXITNIHILO.ConditionTypeStupefied",
    unconscious: "EXITNIHILO.ConditionTypeUnconscious",
    undetected: "EXITNIHILO.ConditionTypeUndetected",
    wounded: "EXITNIHILO.ConditionTypeWounded",
};

const weaponCategories = {
    simple: "EXITNIHILO.WeaponTypeSimple",
    martial: "EXITNIHILO.WeaponTypeMartial",
    advanced: "EXITNIHILO.WeaponTypeAdvanced",
    unarmed: "EXITNIHILO.WeaponTypeUnarmed",
};

/** Base weapon types that are considered equivalent for all rules purposes */
const equivalentWeapons = {
    "composite-longbow": "longbow",
    "composite-shortbow": "shortbow",
    "big-boom-gun": "hand-cannon",
    "spoon-gun": "hand-cannon",
} as const;

const preciousMaterialDescriptions = {
    abysium: "EXITNIHILO.PreciousMaterialAbysiumDescription",
    adamantine: "EXITNIHILO.PreciousMaterialAdamantineDescription",
    coldIron: "EXITNIHILO.PreciousMaterialColdIronDescription",
    darkwood: "EXITNIHILO.PreciousMaterialDarkwoodDescription",
    djezet: "EXITNIHILO.PreciousMaterialDjezetDescription",
    dragonhide: "EXITNIHILO.PreciousMaterialDragonhideDescription",
    "grisantian-pelt": "EXITNIHILO.PreciousMaterialGrisantianPeltDescription",
    inubrix: "EXITNIHILO.PreciousMaterialInubrixDescription",
    mithral: "EXITNIHILO.PreciousMaterialMithralDescription",
    noqual: "EXITNIHILO.PreciousMaterialNoqualDescription",
    orichalcum: "EXITNIHILO.PreciousMaterialOrichalcumDescription",
    siccatite: "EXITNIHILO.PreciousMaterialSiccatiteDescription",
    silver: "EXITNIHILO.PreciousMaterialSilverDescription",
    "sisterstone-dusk": "EXITNIHILO.PreciousMaterialSisterstoneDescription",
    "sisterstone-scarlet": "EXITNIHILO.PreciousMaterialSisterstoneDescription",
    sovereignSteel: "EXITNIHILO.PreciousMaterialSovereignSteelDescription",
    warpglass: "EXITNIHILO.PreciousMaterialWarpglassDescription",
};

const traitsDescriptions = {
    aasimar: "EXITNIHILO.TraitDescriptionAasimar",
    aberration: "EXITNIHILO.TraitDescriptionAberration",
    abjuration: "EXITNIHILO.TraitDescriptionAbjuration",
    acid: "EXITNIHILO.TraitDescriptionAcid",
    additive1: "EXITNIHILO.TraitDescriptionAdditive",
    additive2: "EXITNIHILO.TraitDescriptionAdditive",
    additive3: "EXITNIHILO.TraitDescriptionAdditive",
    adjustment: "EXITNIHILO.TraitDescriptionAdjustment",
    aeon: "EXITNIHILO.TraitDescriptionAeon",
    aesir: "EXITNIHILO.TraitDescriptionAesir",
    aftermath: "EXITNIHILO.TraitDescriptionAftermath",
    agathion: "EXITNIHILO.TraitDescriptionAgathion",
    agile: "EXITNIHILO.TraitDescriptionAgile",
    air: "EXITNIHILO.TraitDescriptionAir",
    alchemical: "EXITNIHILO.TraitDescriptionAlchemical",
    alchemist: "EXITNIHILO.TraitDescriptionAlchemist",
    amphibious: "EXITNIHILO.TraitDescriptionAmphibious",
    anadi: "EXITNIHILO.TraitDescriptionAnadi",
    android: "EXITNIHILO.TraitDescriptionAndroid",
    apex: "EXITNIHILO.TraitDescriptionApex",
    aphorite: "EXITNIHILO.TraitDescriptionAphorite",
    arcane: "EXITNIHILO.TraitDescriptionArcane",
    archetype: "EXITNIHILO.TraitDescriptionArchetype",
    artifact: "EXITNIHILO.TraitDescriptionArtifact",
    attached: "EXITNIHILO.TraitDescriptionAttached",
    "attached-to-crossbow-or-firearm": "EXITNIHILO.TraitDescriptionAttached",
    "attached-to-shield": "EXITNIHILO.TraitDescriptionAttached",
    attack: "EXITNIHILO.TraitDescriptionAttack",
    auditory: "EXITNIHILO.TraitDescriptionAuditory",
    aura: "EXITNIHILO.TraitDescriptionAura",
    automaton: "EXITNIHILO.TraitDescriptionAutomaton",
    azarketi: "EXITNIHILO.TraitDescriptionAzarketi",
    backstabber: "EXITNIHILO.TraitDescriptionBackstabber",
    backswing: "EXITNIHILO.TraitDescriptionBackswing",
    barbarian: "EXITNIHILO.TraitDescriptionBarbarian",
    bard: "EXITNIHILO.TraitDescriptionBard",
    beastkin: "EXITNIHILO.TraitDescriptionBeastkin",
    bomb: "EXITNIHILO.TraitDescriptionBomb",
    brutal: "EXITNIHILO.TraitDescriptionBrutal",
    bulwark: "EXITNIHILO.TraitDescriptionBulwark",
    cantrip: "EXITNIHILO.TraitDescriptionCantrip",
    "capacity-3": "EXITNIHILO.TraitDescriptionCapacity",
    "capacity-4": "EXITNIHILO.TraitDescriptionCapacity",
    "capacity-5": "EXITNIHILO.TraitDescriptionCapacity",
    catalyst: "EXITNIHILO.TraitDescriptionCatalyst",
    catfolk: "EXITNIHILO.TraitDescriptionCatfolk",
    champion: "EXITNIHILO.TraitDescriptionChampion",
    changeling: "EXITNIHILO.TraitDescriptionChangeling",
    chaotic: "EXITNIHILO.TraitDescriptionChaotic",
    charm: "EXITNIHILO.TraitDescriptionCharm",
    class: "EXITNIHILO.TraitDescriptionClass",
    cleric: "EXITNIHILO.TraitDescriptionCleric",
    climbing: "EXITNIHILO.TraitDescriptionClimbing",
    clockwork: "EXITNIHILO.TraitDescriptionClockwork",
    cobbled: "EXITNIHILO.TraitDescriptionCobbled",
    cold: "EXITNIHILO.TraitDescriptionCold",
    combination: "EXITNIHILO.TraitDescriptionCombination",
    comfort: "EXITNIHILO.TraitDescriptionComfort",
    common: "EXITNIHILO.TraitDescriptionCommon",
    companion: "EXITNIHILO.TraitDescriptionCompanion",
    complex: "EXITNIHILO.TraitDescriptionComplex",
    composition: "EXITNIHILO.TraitDescriptionComposition",
    concealable: "EXITNIHILO.TraitDescriptionConcealable",
    concentrate: "EXITNIHILO.TraitDescriptionConcentrate",
    concussive: "EXITNIHILO.TraitDescriptionConcussive",
    conjuration: "EXITNIHILO.TraitDescriptionConjuration",
    conrasu: "EXITNIHILO.TraitDescriptionConrasu",
    consecration: "EXITNIHILO.TraitDescriptionConsecration",
    consumable: "EXITNIHILO.TraitDescriptionConsumable",
    contact: "EXITNIHILO.TraitDescriptionContact",
    contingency: "EXITNIHILO.TraitDescriptionContingency",
    contract: "EXITNIHILO.TraitDescriptionContract",
    "critical-fusion": "EXITNIHILO.TraitDescriptionCriticalFusion",
    curse: "EXITNIHILO.TraitDescriptionCurse",
    cursebound: "EXITNIHILO.TraitDescriptionCursebound",
    cursed: "EXITNIHILO.TraitDescriptionCursed",
    darkness: "EXITNIHILO.TraitDescriptionDarkness",
    darvakka: "EXITNIHILO.TraitDescriptionDarvakka",
    "deadly-2d10": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-2d12": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-2d8": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-3d10": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-3d12": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-3d8": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-4d10": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-4d12": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-4d8": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-d10": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-d12": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-d6": "EXITNIHILO.TraitDescriptionDeadly",
    "deadly-d8": "EXITNIHILO.TraitDescriptionDeadly",
    death: "EXITNIHILO.TraitDescriptionDeath",
    dedication: "EXITNIHILO.TraitDescriptionDedication",
    detection: "EXITNIHILO.TraitDescriptionDetection",
    deviant: "EXITNIHILO.TraitDescriptionDeviant",
    dhampir: "EXITNIHILO.TraitDescriptionDhampir",
    disarm: "EXITNIHILO.TraitDescriptionDisarm",
    disease: "EXITNIHILO.TraitDescriptionDisease",
    divination: "EXITNIHILO.TraitDescriptionDivination",
    divine: "EXITNIHILO.TraitDescriptionDivine",
    "double-barrel": "EXITNIHILO.TraitDescriptionDoubleBarrel",
    downtime: "EXITNIHILO.TraitDescriptionDowntime",
    drug: "EXITNIHILO.TraitDescriptionDrug",
    druid: "EXITNIHILO.TraitDescriptionDruid",
    duskwalker: "EXITNIHILO.TraitDescriptionDuskwalker",
    dwarf: "EXITNIHILO.TraitDescriptionDwarf",
    earth: "EXITNIHILO.TraitDescriptionEarth",
    eidolon: "EXITNIHILO.TraitDescriptionEidolon",
    electricity: "EXITNIHILO.TraitDescriptionElectricity",
    elf: "EXITNIHILO.TraitDescriptionElf",
    elixir: "EXITNIHILO.TraitDescriptionElixir",
    emotion: "EXITNIHILO.TraitDescriptionEmotion",
    enchantment: "EXITNIHILO.TraitDescriptionEnchantment",
    environment: "EXITNIHILO.TraitDescriptionEnvironment",
    esoterica: "EXITNIHILO.TraitDescriptionEsoterica",
    evil: "EXITNIHILO.TraitDescriptionEvil",
    evocation: "EXITNIHILO.TraitDescriptionEvocation",
    exploration: "EXITNIHILO.TraitDescriptionExploration",
    extradimensional: "EXITNIHILO.TraitDescriptionExtradimensional",
    "fatal-aim-d10": "EXITNIHILO.TraitDescriptionFatalAim",
    "fatal-aim-d12": "EXITNIHILO.TraitDescriptionFatalAim",
    "fatal-d10": "EXITNIHILO.TraitDescriptionFatal",
    "fatal-d12": "EXITNIHILO.TraitDescriptionFatal",
    "fatal-d8": "EXITNIHILO.TraitDescriptionFatal",
    fear: "EXITNIHILO.TraitDescriptionFear",
    fetchling: "EXITNIHILO.TraitDescriptionFetchling",
    fey: "EXITNIHILO.TraitDescriptionFey",
    fighter: "EXITNIHILO.TraitDescriptionFighter",
    finesse: "EXITNIHILO.TraitDescriptionFinesse",
    finisher: "EXITNIHILO.TraitDescriptionFinisher",
    fire: "EXITNIHILO.TraitDescriptionFire",
    fleshwarp: "EXITNIHILO.TraitDescriptionFleshwarp",
    flexible: "EXITNIHILO.TraitDescriptionFlexible",
    flourish: "EXITNIHILO.TraitDescriptionFlourish",
    focused: "EXITNIHILO.TraitDescriptionFocused",
    force: "EXITNIHILO.TraitDescriptionForce",
    forceful: "EXITNIHILO.TraitDescriptionForceful",
    fortune: "EXITNIHILO.TraitDescriptionFortune",
    "free-hand": "EXITNIHILO.TraitDescriptionFreeHand",
    fulu: "EXITNIHILO.TraitDescriptionFulu",
    fungus: "EXITNIHILO.TraitDescriptionFungus",
    gadget: "EXITNIHILO.TraitDescriptionGadget",
    ganzi: "EXITNIHILO.TraitDescriptionGanzi",
    general: "EXITNIHILO.TraitDescriptionGeneral",
    genie: "EXITNIHILO.TraitDescriptionGenie",
    geniekin: "EXITNIHILO.TraitDescriptionGeniekin",
    ghoran: "EXITNIHILO.TraitDescriptionGhoran",
    ghul: "EXITNIHILO.TraitDescriptionGhul",
    gnoll: "EXITNIHILO.TraitDescriptionGnoll",
    gnome: "EXITNIHILO.TraitDescriptionGnome",
    goblin: "EXITNIHILO.TraitDescriptionGoblin",
    goloma: "EXITNIHILO.TraitDescriptionGoloma",
    good: "EXITNIHILO.TraitDescriptionGood",
    grapple: "EXITNIHILO.TraitDescriptionGrapple",
    grimoire: "EXITNIHILO.TraitDescriptionGrimoire",
    grippli: "EXITNIHILO.TraitDescriptionGrippli",
    gunslinger: "EXITNIHILO.TraitDescriptionGunslinger",
    halfling: "EXITNIHILO.TraitDescriptionHalfling",
    "half-elf": "EXITNIHILO.TraitDescriptionHalfElf",
    "half-orc": "EXITNIHILO.TraitDescriptionHalfOrc",
    "jousting-d6": "EXITNIHILO.TraitDescriptionJoustingD6",
    hampering: "EXITNIHILO.TraitDescriptionHampering",
    haunt: "EXITNIHILO.TraitDescriptionHaunt",
    healing: "EXITNIHILO.TraitDescriptionHealing",
    hex: "EXITNIHILO.TraitDescriptionHex",
    hobgoblin: "EXITNIHILO.TraitDescriptionHobgoblin",
    human: "EXITNIHILO.TraitDescriptionHuman",
    humanoid: "EXITNIHILO.TraitDescriptionHumanoid",
    ifrit: "EXITNIHILO.TraitDescriptionIfrit",
    illusion: "EXITNIHILO.TraitDescriptionIllusion",
    incapacitation: "EXITNIHILO.TraitDescriptionIncapacitation",
    incarnate: "EXITNIHILO.TraitDescriptionIncarnate",
    incorporeal: "EXITNIHILO.TraitDescriptionIncorporeal",
    infused: "EXITNIHILO.TraitDescriptionInfused",
    ingested: "EXITNIHILO.TraitDescriptionIngested",
    inhaled: "EXITNIHILO.TraitDescriptionInhaled",
    injection: "EXITNIHILO.TraitDescriptionInjection",
    injury: "EXITNIHILO.TraitDescriptionInjury",
    intelligent: "EXITNIHILO.TraitDescriptionIntelligent",
    inventor: "EXITNIHILO.TraitDescriptionInventor",
    invested: "EXITNIHILO.TraitDescriptionInvested",
    investigator: "EXITNIHILO.TraitDescriptionInvestigator",
    kashrishi: "EXITNIHILO.TraitDescriptionKashrishi",
    kickback: "EXITNIHILO.TraitDescriptionKickback",
    kitsune: "TraitDescriptionKitsune",
    kobold: "TraitDescriptionKobold",
    lawful: "EXITNIHILO.TraitDescriptionLawful",
    leshy: "EXITNIHILO.TraitDescriptionLeshy",
    light: "EXITNIHILO.TraitDescriptionLight",
    linguistic: "EXITNIHILO.TraitDescriptionLinguistic",
    litany: "EXITNIHILO.TraitDescriptionLitany",
    lizardfolk: "EXITNIHILO.TraitDescriptionLizardfolk",
    magical: "EXITNIHILO.TraitDescriptionMagical",
    magus: "EXITNIHILO.TraitDescriptionMagus",
    manipulate: "EXITNIHILO.TraitDescriptionManipulate",
    mechanical: "EXITNIHILO.TraitDescriptionMechanical",
    mental: "EXITNIHILO.TraitDescriptionMental",
    metal: "EXITNIHILO.TraitDescriptionMetal",
    metamagic: "EXITNIHILO.TraitDescriptionMetamagic",
    mindless: "EXITNIHILO.TraitDescriptionMindless",
    minion: "EXITNIHILO.TraitDescriptionMinion",
    misfortune: "EXITNIHILO.TraitDescriptionMisfortune",
    modification: "EXITNIHILO.TraitDescriptionModification",
    modular: "EXITNIHILO.TraitDescriptionModular",
    monk: "EXITNIHILO.TraitDescriptionMonk",
    morph: "EXITNIHILO.TraitDescriptionMorph",
    mounted: "EXITNIHILO.TraitDescriptionMounted",
    move: "EXITNIHILO.TraitDescriptionMove",
    multiclass: "EXITNIHILO.TraitDescriptionMulticlass",
    mutagen: "EXITNIHILO.TraitDescriptionMutagen",
    nagaji: "EXITNIHILO.TraitDescriptionNagaji",
    necromancy: "EXITNIHILO.TraitDescriptionNecromancy",
    negative: "EXITNIHILO.TraitDescriptionNegative",
    noisy: "EXITNIHILO.TraitDescriptionNoisy",
    nonlethal: "EXITNIHILO.TraitDescriptionNonlethal",
    oath: "EXITNIHILO.TraitDescriptionOath",
    occult: "EXITNIHILO.TraitDescriptionOccult",
    oil: "EXITNIHILO.TraitDescriptionOil",
    olfactory: "EXITNIHILO.TraitDescriptionOlfactory",
    open: "EXITNIHILO.TraitDescriptionOpen",
    oracle: "EXITNIHILO.TraitDescriptionOracle",
    orc: "EXITNIHILO.TraitDescriptionOrc",
    oread: "EXITNIHILO.TraitDescriptionOread",
    parry: "EXITNIHILO.TraitDescriptionParry",
    peachwood: "EXITNIHILO.PreciousMaterialPeachwoodDescription",
    plant: "EXITNIHILO.TraitDescriptionPlant",
    poison: "EXITNIHILO.TraitDescriptionPoison",
    polymorph: "EXITNIHILO.TraitDescriptionPolymorph",
    poppet: "EXITNIHILO.TraitDescriptionPoppet",
    portable: "EXITNIHILO.TraitDescriptionPortable",
    positive: "EXITNIHILO.TraitDescriptionPositive",
    possession: "EXITNIHILO.TraitDescriptionPossession",
    potion: "EXITNIHILO.TraitDescriptionPotion",
    precious: "EXITNIHILO.TraitDescriptionPrecious",
    prediction: "EXITNIHILO.TraitDescriptionPrediction",
    press: "EXITNIHILO.TraitDescriptionPress",
    primal: "EXITNIHILO.TraitDescriptionPrimal",
    propulsive: "EXITNIHILO.TraitDescriptionPropulsive",
    psyche: "EXITNIHILO.TraitDescriptionPsyche",
    psychic: "EXITNIHILO.TraitDescriptionPsychic",
    rage: "EXITNIHILO.TraitDescriptionRage",
    ranger: "EXITNIHILO.TraitDescriptionRanger",
    "ranged-trip": "EXITNIHILO.TraitDescriptionRangedTrip",
    rare: "EXITNIHILO.TraitDescriptionRare",
    ratfolk: "EXITNIHILO.TraitDescriptionRatfolk",
    reach: "EXITNIHILO.TraitDescriptionReach",
    "reach-0": "EXITNIHILO.TraitDescriptionReach",
    "reach-10": "EXITNIHILO.TraitDescriptionReach",
    "reach-100": "EXITNIHILO.TraitDescriptionReach",
    "reach-1000": "EXITNIHILO.TraitDescriptionReach",
    "reach-15": "EXITNIHILO.TraitDescriptionReach",
    "reach-20": "EXITNIHILO.TraitDescriptionReach",
    "reach-25": "EXITNIHILO.TraitDescriptionReach",
    "reach-30": "EXITNIHILO.TraitDescriptionReach",
    "reach-40": "EXITNIHILO.TraitDescriptionReach",
    "reach-50": "EXITNIHILO.TraitDescriptionReach",
    "reach-60": "EXITNIHILO.TraitDescriptionReach",
    reflection: "EXITNIHILO.TraitDescriptionReflection",
    reload: "EXITNIHILO.TraitDescriptionReload",
    "reload-0": "EXITNIHILO.TraitDescriptionReload",
    "reload-1": "EXITNIHILO.TraitDescriptionReload",
    "reload-1-min": "EXITNIHILO.TraitDescriptionReload",
    "reload-2": "EXITNIHILO.TraitDescriptionReload",
    repeating: "EXITNIHILO.TraitDescriptionRepeating",
    resonant: "EXITNIHILO.TraitDescriptionResonant",
    revelation: "EXITNIHILO.TraitDescriptionRevelation",
    rogue: "EXITNIHILO.TraitDescriptionRogue",
    saggorak: "EXITNIHILO.TraitDescriptionSaggorak",
    "scatter-10": "EXITNIHILO.TraitDescriptionScatter",
    "scatter-15": "EXITNIHILO.TraitDescriptionScatter",
    "scatter-5": "EXITNIHILO.TraitDescriptionScatter",
    scroll: "EXITNIHILO.TraitDescriptionScroll",
    scrying: "EXITNIHILO.TraitDescriptionScrying",
    secret: "EXITNIHILO.TraitDescriptionSecret",
    shadow: "EXITNIHILO.TraitDescriptionShadow",
    shisk: "EXITNIHILO.TraitDescriptionShisk",
    shoony: "EXITNIHILO.TraitDescriptionShoony",
    shove: "EXITNIHILO.TraitDescriptionShove",
    skeleton: "EXITNIHILO.TraitDescriptionSkeleton",
    skill: "EXITNIHILO.TraitDescriptionSkill",
    sleep: "EXITNIHILO.TraitDescriptionSleep",
    snare: "EXITNIHILO.TraitDescriptionSnare",
    social: "EXITNIHILO.TraitDescriptionSocial",
    sonic: "EXITNIHILO.TraitDescriptionSonic",
    sorcerer: "EXITNIHILO.TraitDescriptionSorcerer",
    spellheart: "EXITNIHILO.TraitDescriptionSpellheart",
    spellshot: "EXITNIHILO.TraitNoDescription",
    splash: "EXITNIHILO.TraitDescriptionSplash",
    "splash-10": "EXITNIHILO.TraitDescriptionSplash10",
    sprite: "EXITNIHILO.TraitDescriptionSprite",
    staff: "EXITNIHILO.TraitDescriptionStaff",
    stance: "EXITNIHILO.TraitDescriptionStance",
    steam: "EXITNIHILO.TraitDescriptionSteam",
    strix: "EXITNIHILO.TraitDescriptionStrix",
    structure: "EXITNIHILO.TraitDescriptionStructure",
    suli: "EXITNIHILO.TraitDescriptionSuli",
    summon: "EXITNIHILO.TraitDescriptionSummon",
    summoned: "EXITNIHILO.TraitDescriptionSummoned",
    summoner: "EXITNIHILO.TraitDescriptionSummoner",
    swashbuckler: "EXITNIHILO.TraitDescriptionSwashbuckler",
    sweep: "EXITNIHILO.TraitDescriptionSweep",
    sylph: "EXITNIHILO.TraitDescriptionSylph",
    talisman: "EXITNIHILO.TraitDescriptionTalisman",
    tattoo: "EXITNIHILO.TraitDescriptionTattoo",
    tech: "EXITNIHILO.TraitDescriptionTech",
    telepathy: "EXITNIHILO.TraitDescriptionTelepathy",
    teleportation: "EXITNIHILO.TraitDescriptionTeleportation",
    tengu: "EXITNIHILO.TraitDescriptionTengu",
    tethered: "EXITNIHILO.TraitDescriptionTethered",
    thaumaturge: "EXITNIHILO.TraitDescriptionThaumaturge",
    thrown: "EXITNIHILO.TraitDescriptionThrown",
    "thrown-10": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-100": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-15": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-20": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-200": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-25": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-30": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-40": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-50": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-60": "EXITNIHILO.TraitDescriptionThrown",
    "thrown-80": "EXITNIHILO.TraitDescriptionThrown",
    tiefling: "EXITNIHILO.TraitDescriptionTiefling",
    time: "EXITNIHILO.TraitDescriptionTime",
    transmutation: "EXITNIHILO.TraitDescriptionTransmutation",
    trap: "EXITNIHILO.TraitDescriptionTrap",
    trip: "EXITNIHILO.TraitDescriptionTrip",
    "true-name": "EXITNIHILO.TraitDescriptionTrueName",
    twin: "EXITNIHILO.TraitDescriptionTwin",
    "two-hand-d10": "EXITNIHILO.TraitDescriptionTwoHand",
    "two-hand-d12": "EXITNIHILO.TraitDescriptionTwoHand",
    "two-hand-d6": "EXITNIHILO.TraitDescriptionTwoHand",
    "two-hand-d8": "EXITNIHILO.TraitDescriptionTwoHand",
    unarmed: "EXITNIHILO.TraitDescriptionUnarmed",
    uncommon: "EXITNIHILO.TraitDescriptionUncommon",
    undine: "EXITNIHILO.TraitDescriptionUndine",
    unique: "EXITNIHILO.TraitDescriptionUnique",
    unstable: "EXITNIHILO.TraitDescriptionUnstable",
    vanara: "EXITNIHILO.TraitDescriptionVanara",
    vishkanya: "EXITNIHILO.TraitDescriptionVishkanya",
    "versatile-acid": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-b": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-chaotic": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-cold": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-electricity": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-evil": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-fire": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-force": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-good": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-lawful": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-negative": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-p": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-positive": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-s": "EXITNIHILO.TraitDescriptionVersatile",
    "versatile-sonic": "EXITNIHILO.TraitDescriptionVersatile",
    virulent: "EXITNIHILO.TraitDescriptionVirulent",
    visual: "EXITNIHILO.TraitDescriptionVisual",
    "volley-20": "EXITNIHILO.TraitDescriptionVolley",
    "volley-30": "EXITNIHILO.TraitDescriptionVolley",
    "volley-50": "EXITNIHILO.TraitDescriptionVolley",
    wand: "EXITNIHILO.TraitDescriptionWand",
    water: "EXITNIHILO.TraitDescriptionWater",
    witch: "EXITNIHILO.TraitDescriptionWitch",
    wizard: "EXITNIHILO.TraitDescriptionWizard",
    ...preciousMaterialDescriptions,
};

export const EXITNIHILOCONFIG = {
    chatDamageButtonShieldToggle: false,

    roles : {
        protecteur: "EXITNIHILO.Personnage.Roles.Protecteur.Titre",
        approvisionneur: "EXITNIHILO.Personnage.Roles.Approvisionneur.Titre",
        dirigeant: "EXITNIHILO.Personnage.Roles.Dirigeant.Titre",
        animateur: "EXITNIHILO.Personnage.Roles.Animateur.Titre",
        soigneur: "EXITNIHILO.Personnage.Roles.Soigneur.Titre",
        sachant: "EXITNIHILO.Personnage.Roles.Sachant.Titre",
        bricoleur: "EXITNIHILO.Personnage.Roles.Bricoleur.Titre",
    },

    statusEffects: {
        lastIconTheme: "default" as StatusEffectIconTheme,
        iconDir: "systems/exit-nihilo/icons/conditions/",
        conditions: tokenHUDConditions,
    },

    actorTypes,

    levels: {
        1: "EXITNIHILO.Level1",
        2: "EXITNIHILO.Level2",
        3: "EXITNIHILO.Level3",
        4: "EXITNIHILO.Level4",
        5: "EXITNIHILO.Level5",
        6: "EXITNIHILO.Level6",
        7: "EXITNIHILO.Level7",
        8: "EXITNIHILO.Level8",
        9: "EXITNIHILO.Level9",
        10: "EXITNIHILO.Level10",
        11: "EXITNIHILO.Level11",
        12: "EXITNIHILO.Level12",
        13: "EXITNIHILO.Level13",
        14: "EXITNIHILO.Level14",
        15: "EXITNIHILO.Level15",
        16: "EXITNIHILO.Level16",
        17: "EXITNIHILO.Level17",
        18: "EXITNIHILO.Level18",
        19: "EXITNIHILO.Level19",
        20: "EXITNIHILO.Level20",
    },

    abilities: {
        str: "EXITNIHILO.AbilityStr",
        dex: "EXITNIHILO.AbilityDex",
        con: "EXITNIHILO.AbilityCon",
        int: "EXITNIHILO.AbilityInt",
        wis: "EXITNIHILO.AbilityWis",
        cha: "EXITNIHILO.AbilityCha",
    },

    attributes: {
        perception: "EXITNIHILO.PerceptionLabel",
        stealth: "EXITNIHILO.StealthLabel",
        initiative: "EXITNIHILO.PerceptionLabel",
    },

    dcAdjustments: {
        "incredibly easy": "EXITNIHILO.DCAdjustmentIncrediblyEasy",
        "very easy": "EXITNIHILO.DCAdjustmentVeryEasy",
        easy: "EXITNIHILO.DCAdjustmentEasy",
        normal: "EXITNIHILO.DCAdjustmentNormal",
        hard: "EXITNIHILO.DCAdjustmentHard",
        "very hard": "EXITNIHILO.DCAdjustmentVeryHard",
        "incredibly hard": "EXITNIHILO.DCAdjustmentIncrediblyHard",
    },

    skills: {
        acr: "EXITNIHILO.SkillAcr",
        arc: "EXITNIHILO.SkillArc",
        ath: "EXITNIHILO.SkillAth",
        cra: "EXITNIHILO.SkillCra",
        dec: "EXITNIHILO.SkillDec",
        dip: "EXITNIHILO.SkillDip",
        itm: "EXITNIHILO.SkillItm",
        med: "EXITNIHILO.SkillMed",
        nat: "EXITNIHILO.SkillNat",
        occ: "EXITNIHILO.SkillOcc",
        prf: "EXITNIHILO.SkillPrf",
        rel: "EXITNIHILO.SkillRel",
        soc: "EXITNIHILO.SkillSoc",
        ste: "EXITNIHILO.SkillSte",
        sur: "EXITNIHILO.SkillSur",
        thi: "EXITNIHILO.SkillThi",
    },

    martialSkills: {
        unarmored: "EXITNIHILO.MartialUnarmored",
        light: "EXITNIHILO.MartialLight",
        medium: "EXITNIHILO.MartialMedium",
        heavy: "EXITNIHILO.MartialHeavy",
        simple: "EXITNIHILO.MartialSimple",
        martial: "EXITNIHILO.MartialMartial",
        advanced: "EXITNIHILO.MartialAdvanced",
        unarmed: "EXITNIHILO.MartialUnarmed",
    },

    saves: {
        fortitude: "EXITNIHILO.SavesFortitude",
        reflex: "EXITNIHILO.SavesReflex",
        will: "EXITNIHILO.SavesWill",
    },

    savingThrowDefaultAbilities: {
        fortitude: "con",
        reflex: "dex",
        will: "wis",
    } as const,

    currencies: {
        pp: "EXITNIHILO.CurrencyPP",
        gp: "EXITNIHILO.CurrencyGP",
        sp: "EXITNIHILO.CurrencySP",
        cp: "EXITNIHILO.CurrencyCP",
    },

    armorPotencyRunes: {
        "1": "EXITNIHILO.ArmorPotencyRune1",
        "2": "EXITNIHILO.ArmorPotencyRune2",
        "3": "EXITNIHILO.ArmorPotencyRune3",
        "4": "EXITNIHILO.ArmorPotencyRune4",
    },

    armorResiliencyRunes: {
        resilient: "EXITNIHILO.ArmorResilientRune",
        greaterResilient: "EXITNIHILO.ArmorGreaterResilientRune",
        majorResilient: "EXITNIHILO.ArmorMajorResilientRune",
    },
    armorPropertyRunes: {
        ready: "EXITNIHILO.ArmorPropertyRuneReady",
        slick: "EXITNIHILO.ArmorPropertyRuneSlick",
        shadow: "EXITNIHILO.ArmorPropertyRuneShadow",
        glamered: "EXITNIHILO.ArmorPropertyRuneGlamered",
        acidResistant: "EXITNIHILO.ArmorPropertyRuneAcidResistant",
        coldResistant: "EXITNIHILO.ArmorPropertyRuneColdResistant",
        electricityResistant: "EXITNIHILO.ArmorPropertyRuneElectricityResistant",
        fireResistant: "EXITNIHILO.ArmorPropertyRuneFireResistant",
        greaterSlick: "EXITNIHILO.ArmorPropertyRuneGreaterSlick",
        invisibility: "EXITNIHILO.ArmorPropertyRuneInvisibility",
        sinisterKnight: "EXITNIHILO.ArmorPropertyRuneSinisterKnight",
        greaterDread: "EXITNIHILO.ArmorPropertyRuneGreaterDread",
        greaterReady: "EXITNIHILO.ArmorPropertyRuneGreaterReady",
        greaterShadow: "EXITNIHILO.ArmorPropertyRuneGreaterShadow",
        greaterInvisibility: "EXITNIHILO.ArmorPropertyRuneGreaterInvisibility",
        greaterAcidResistant: "EXITNIHILO.ArmorPropertyRuneGreaterAcidResistant",
        greaterColdResistant: "EXITNIHILO.ArmorPropertyRuneGreaterColdResistant",
        greaterElectricityResistant: "EXITNIHILO.ArmorPropertyRuneGreaterElectricityResistant",
        greaterFireResistant: "EXITNIHILO.ArmorPropertyRuneGreaterFireResistant",
        fortification: "EXITNIHILO.ArmorPropertyRuneFortification",
        winged: "EXITNIHILO.ArmorPropertyRuneWinged",
        rockBraced: "EXITNIHILO.ArmorPropertyRuneRockBraced",
        soaring: "EXITNIHILO.ArmorPropertyRuneSoaring",
        antimagic: "EXITNIHILO.ArmorPropertyRuneAntimagic",
        majorSlick: "EXITNIHILO.ArmorPropertyRuneMajorSlick",
        ethereal: "EXITNIHILO.ArmorPropertyRuneEthereal",
        majorShadow: "EXITNIHILO.ArmorPropertyRuneMajorShadow",
        moderateDread: "EXITNIHILO.ArmorPropertyRuneModerateDread",
        greaterFortification: "EXITNIHILO.ArmorPropertyRuneGreaterFortification",
        greaterWinged: "EXITNIHILO.ArmorPropertyRuneGreaterWinged",
        deathless: "EXITNIHILO.ArmorPropertyRuneDeathless",
        dread: "EXITNIHILO.ArmorPropertyRuneDread",
        bitter: "EXITNIHILO.ArmorPropertyRuneBitter",
        stanching: "EXITNIHILO.ArmorPropertyRuneStanching",
        greaterStanching: "EXITNIHILO.ArmorPropertyRuneGreaterStanching",
        majorStanching: "EXITNIHILO.ArmorPropertyRuneMajorStanching",
        trueStanching: "EXITNIHILO.ArmorPropertyRuneTrueStanching",
        implacable: "EXITNIHILO.ArmorPropertyRuneImplacable",
    },
    accessoryPropertyRunes: {
        called: "EXITNIHILO.AccessoryPropertyRuneCalled",
        dragonsBreath: "EXITNIHILO.AccessoryPropertyRuneDragonsBreath",
        paired: "EXITNIHILO.AccessoryPropertyRunePaired",
        greaterPaired: "EXITNIHILO.AccessoryPropertyRuneGreaterPaired",
        majorPaired: "EXITNIHILO.AccessoryPropertyRuneMajorPaired",
        presentable: "EXITNIHILO.AccessoryPropertyRunePresentable",
        snagging: "EXITNIHILO.AccessoryPropertyRuneSnagging",
        softLanding: "EXITNIHILO.AccessoryPropertyRuneSoftLanding",
        spellBastion: "EXITNIHILO.AccessoryPropertyRuneSpellBastion",
        windCatcher: "EXITNIHILO.AccessoryPropertyRuneWindCatcher",
        greaterWindCatcher: "EXITNIHILO.AccessoryPropertyRuneGreaterWindCatcher",
    },
    weaponPotencyRunes: {
        1: "EXITNIHILO.WeaponPotencyRune1",
        2: "EXITNIHILO.WeaponPotencyRune2",
        3: "EXITNIHILO.WeaponPotencyRune3",
        4: "EXITNIHILO.WeaponPotencyRune4",
    },
    weaponStrikingRunes: {
        striking: "EXITNIHILO.ArmorStrikingRune",
        greaterStriking: "EXITNIHILO.ArmorGreaterStrikingRune",
        majorStriking: "EXITNIHILO.ArmorMajorStrikingRune",
    },
    damageSubtypes: {
        persistent: "EXITNIHILO.ConditionTypePersistentShort",
        splash: "EXITNIHILO.TraitSplash",
    },

    stackGroups: {
        arrows: "EXITNIHILO.StackGroupArrows",
        bolts: "EXITNIHILO.StackGroupBolts",
        slingBullets: "EXITNIHILO.StackGroupSlingBullets",
        blowgunDarts: "EXITNIHILO.StackGroupBlowgunDarts",
        woodenTaws: "EXITNIHILO.StackGroupWoodenTaws",
        rounds5: "EXITNIHILO.StackGroupRounds5",
        rounds10: "EXITNIHILO.StackGroupRounds10",
        rations: "EXITNIHILO.StackGroupRations",
        coins: "EXITNIHILO.StackGroupCoins",
        gems: "EXITNIHILO.StackGroupGems",
        sacks: "EXITNIHILO.StackGroupSacks",
    },

    weaponDamage: {
        bludgeoning: "EXITNIHILO.TraitBludgeoning",
        piercing: "EXITNIHILO.TraitPiercing",
        slashing: "EXITNIHILO.TraitSlashing",
        modular: "EXITNIHILO.TraitModular",
    },

    healingTypes: {
        healing: "EXITNIHILO.TraitHealing",
        temphp: "EXITNIHILO.HealingTypeTemporaryHealing",
    },

    weaponCategories,
    equivalentWeapons,

    weaponDescriptions: {
        club: "EXITNIHILO.WeaponDescriptionClub",
        knife: "EXITNIHILO.WeaponDescriptionKnife",
        brawling: "EXITNIHILO.WeaponDescriptionBrawling",
        spear: "EXITNIHILO.WeaponDescriptionSpear",
        sword: "EXITNIHILO.WeaponDescriptionSword",
        axe: "EXITNIHILO.WeaponDescriptionAxe",
        flail: "EXITNIHILO.WeaponDescriptionFlail",
        polearm: "EXITNIHILO.WeaponDescriptionPolearm",
        pick: "EXITNIHILO.WeaponDescriptionPick",
        hammer: "EXITNIHILO.WeaponDescriptionHammer",
        shield: "EXITNIHILO.WeaponDescriptionShield",
        dart: "EXITNIHILO.WeaponDescriptionDart",
        bow: "EXITNIHILO.WeaponDescriptionBow",
        sling: "EXITNIHILO.WeaponDescriptionSling",
        bomb: "EXITNIHILO.WeaponDescriptionBomb",
    },

    usageTraits: {
        "affixed-to-a-ranged-weapon": "EXITNIHILO.TraitAffixedToARangedWeapon",
        "affixed-to-a-shield": "EXITNIHILO.TraitAffixedToAShield",
        "affixed-to-a-two-handed-firearm-or-crossbow": "EXITNIHILO.TraitAffixededToATwoHandedFirearmOrCrossbow",
        "affixed-to-armor": "EXITNIHILO.TraitAffixedToArmor",
        "affixed-to-medium-heavy-armor": "EXITNIHILO.TraitAffixedToMediumHeavyArmor",
        "affixed-to-armor-or-a-weapon": "EXITNIHILO.TraitAffixedToArmorOrAWeapon",
        "affixed-to-armor-or-travelers-clothing": "EXITNIHILO.TraitAffixedToArmorOrTravelersClothing",
        "affixed-to-crossbow-or-firearm": "EXITNIHILO.TraitAffixededToCrossbowOrFirearm",
        "affixed-to-firearm": "EXITNIHILO.TraitAffixededToFirearm",
        "affixed-to-firearm-with-a-reload-of-1": "EXITNIHILO.TraitAffixededToFirearmWithAReloadOf1",
        "affixed-to-firearm-with-the-kickback-trait": "EXITNIHILO.TraitAffixededToFirearmWithTheKickbackTrait",
        "affixed-to-headgear": "EXITNIHILO.TraitAffixedToHeadgear",
        "affixed-to-weapon": "EXITNIHILO.TraitAffixedToWeapon",
        "applied-to-a-wind-powered-vehicle": "EXITNIHILO.TraitAppliedToAWindPoweredVehicle",
        "applied-to-any-item-of-light-or-negligible-bulk": "EXITNIHILO.TraitAppliedToAnyItemOfLightOrNegligibleBulk",
        "applied-to-any-visible-article-of-clothing": "EXITNIHILO.TraitAppliedToAnyVisibleArticleOfClothing",
        "applied-to-belt-cape-cloak-or-scarf": "EXITNIHILO.TraitAppliedToBeltCapeCloakOrScarf",
        "applied-to-boots-cape-cloak-or-umbrella": "EXITNIHILO.TraitAppliedToBootsCapeCloakOrUmbrella",
        "applied-to-dueling-cape-or-shield": "EXITNIHILO.TraitAppliedToDuelingCapeOrShield",
        "applied-to-buckler-shield": "EXITNIHILO.TraitAppliedToBucklerShield",
        "applied-to-shield": "EXITNIHILO.TraitAppliedToShield",
        "attached-to-a-thrown-weapon": "EXITNIHILO.TraitAttachedToAThrownWeapon",
        "attached-to-crossbow-or-firearm": "EXITNIHILO.TraitAttachedToCrossbowOrFirearm",
        "attached-to-crossbow-or-firearm-firing-mechanism": "EXITNIHILO.TraitAttachedToCrossbowOrFirearmFiringMechanism",
        "attached-to-crossbow-or-firearm-scope": "EXITNIHILO.TraitAttachedToCrossbowOrFirearmScope",
        "attached-to-firearm": "EXITNIHILO.TraitAttachedToFirearm",
        "attached-to-firearm-scope": "EXITNIHILO.TraitAttachedToFirearmScope",
        bonded: "EXITNIHILO.TraitBonded",
        "each-rune-applied-to-a-separate-item-that-has-pockets":
            "EXITNIHILO.TraitEachRuneAppliedToASeparateItemThatHasPockets",
        "etched-onto-a-weapon": "EXITNIHILO.TraitEtchedOntoAWeapon",
        "etched-onto-armor": "EXITNIHILO.TraitEtchedOntoArmor",
        "etched-onto-clan-dagger": "EXITNIHILO.TraitEtchedOntoAClanDagger",
        "etched-onto-lm-nonmetal-armor": "EXITNIHILO.TraitEtchedOntoLightMedNMArmor",
        "etched-onto-med-heavy-armor": "EXITNIHILO.TraitEtchedOntoMedHeavyArmor",
        "etched-onto-melee-weapon": "EXITNIHILO.TraitEtchedOntoAMeleeWeapon",
        "etched-onto-thrown-weapon": "EXITNIHILO.TraitEtchedOntoAThrownWeapon",
        "held-in-one-hand": "EXITNIHILO.TraitHeldOneHand",
        "held-in-two-hands": "EXITNIHILO.TraitHeldTwoHands",
        other: "Other",
        "sewn-into-clothing": "EXITNIHILO.TraitSewnIntoClothing",
        "tattooed-on-the-body": "EXITNIHILO.TraitTattooedOnTheBody",
        worn: "EXITNIHILO.TraitWorn",
        wornamulet: "EXITNIHILO.TraitWornAmulet",
        wornanklets: "EXITNIHILO.TraitWornAnklets",
        wornarmbands: "EXITNIHILO.TraitWornArmbands",
        wornbackpack: "EXITNIHILO.TraitWornBackpack",
        wornbarding: "EXITNIHILO.TraitWornBarding",
        wornbelt: "EXITNIHILO.TraitWornBelt",
        wornbeltpouch: "EXITNIHILO.TraitWornBeltPouch",
        wornbracelet: "EXITNIHILO.TraitWornBracelet",
        wornbracers: "EXITNIHILO.TraitWornBracers",
        worncirclet: "EXITNIHILO.TraitWornCirclet",
        worncloak: "EXITNIHILO.TraitWornCloak",
        wornclothing: "EXITNIHILO.TraitWornClothing",
        worncollar: "EXITNIHILO.TraitWornCollar",
        worncrown: "EXITNIHILO.TraitWornCrown",
        wornepaulet: "EXITNIHILO.TraitWornEpaulet",
        worneyepiece: "EXITNIHILO.TraitWornEyepiece",
        worngarment: "EXITNIHILO.TraitWornGarment",
        worngloves: "EXITNIHILO.TraitWornGloves",
        wornheadwear: "EXITNIHILO.TraitWornHeadwear",
        wornhorseshoes: "EXITNIHILO.TraitWornHorseshoes",
        wornmask: "EXITNIHILO.TraitWornMask",
        wornnecklace: "EXITNIHILO.TraitWornNecklace",
        wornonbelt: "EXITNIHILO.TraitWornOnBelt",
        wornoronehand: "EXITNIHILO.TraitWornOrOneHand",
        wornring: "EXITNIHILO.TraitWornRing",
        wornsaddle: "EXITNIHILO.TraitWornSaddle",
        wornshoes: "EXITNIHILO.TraitWornShoes",
        wornwrist: "EXITNIHILO.TraitWornOnWrists",
        "worn-and-attached-to-two-weapons": "EXITNIHILO.TraitWornAndAttachedToTwoWeapons",
        "worn-under-armor": "EXITNIHILO.TraitWornUnderArmor",
    },

    rarityTraits: {
        common: "EXITNIHILO.TraitCommon",
        uncommon: "EXITNIHILO.TraitUncommon",
        rare: "EXITNIHILO.TraitRare",
        unique: "EXITNIHILO.TraitUnique",
    },

    traitsDescriptions,
    actionTraits,    
    armorTraits,
    creatureTraits,
    consumableTraits,
    equipmentTraits,
    monsterTraits: creatureTraits,
    weaponTraits,
    
    weaponHands: {
        1: "EXITNIHILO.WeaponHands1",
        "1+": "EXITNIHILO.WeaponHands1Plus",
        2: "EXITNIHILO.WeaponHands2",
    },

    itemBonuses: {
        "-2": "EXITNIHILO.ItemBonusMinus2",
        0: "EXITNIHILO.ItemBonus0",
        1: "EXITNIHILO.ItemBonus1",
        2: "EXITNIHILO.ItemBonus2",
        3: "EXITNIHILO.ItemBonus3",
    },

    damageDice: {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
    },

    damageDie: {
        d4: "EXITNIHILO.DamageDieD4",
        d6: "EXITNIHILO.DamageDieD6",
        d8: "EXITNIHILO.DamageDieD8",
        d10: "EXITNIHILO.DamageDieD10",
        d12: "EXITNIHILO.DamageDieD12",
    },

    weaponMAP: {
        1: "-1/-2",
        2: "-2/-4",
        3: "-3/-6",
        4: "-4/-8",
        5: "-5/-10",
    },

    armorTypes: {
        unarmored: "EXITNIHILO.ArmorTypeUnarmored",
        light: "EXITNIHILO.ArmorTypeLight",
        medium: "EXITNIHILO.ArmorTypeMedium",
        heavy: "EXITNIHILO.ArmorTypeHeavy",
        shield: "EXITNIHILO.ArmorTypeShield",
    },

    armorGroups: {
        composite: "EXITNIHILO.ArmorGroupComposite",
        chain: "EXITNIHILO.ArmorGroupChain",
        cloth: "EXITNIHILO.ArmorGroupCloth",
        leather: "EXITNIHILO.ArmorGroupLeather",
        plate: "EXITNIHILO.ArmorGroupPlate",
    },

    consumableTypes: {
        ammo: "EXITNIHILO.ConsumableTypeAmmo",
        catalyst: "EXITNIHILO.TraitCatalyst",
        drug: "EXITNIHILO.ConsumableTypeDrug",
        elixir: "EXITNIHILO.ConsumableTypeElixir",
        fulu: "EXITNIHILO.TraitFulu",
        gadget: "EXITNIHILO.TraitGadget",
        oil: "EXITNIHILO.ConsumableTypeOil",
        other: "EXITNIHILO.ConsumableTypeOther",
        mutagen: "EXITNIHILO.ConsumableTypeMutagen",
        poison: "EXITNIHILO.ConsumableTypePoison",
        potion: "EXITNIHILO.ConsumableTypePotion",
        scroll: "EXITNIHILO.ConsumableTypeScroll",
        snare: "EXITNIHILO.ConsumableTypeSnare",
        talisman: "EXITNIHILO.ConsumableTypeTalisman",
        tool: "EXITNIHILO.ConsumableTypeTool",
        wand: "EXITNIHILO.ConsumableTypeWand",
    },

    preparationType: {
        prepared: "EXITNIHILO.PreparationTypePrepared",
        spontaneous: "EXITNIHILO.PreparationTypeSpontaneous",
        innate: "EXITNIHILO.PreparationTypeInnate",
        focus: "EXITNIHILO.SpellCategoryFocus",
        ritual: "EXITNIHILO.SpellCategoryRitual",
        items: "EXITNIHILO.PreparationTypeItems",
    },

    areaTypes: {
        burst: "EXITNIHILO.AreaTypeBurst",
        cone: "EXITNIHILO.AreaTypeCone",
        cube: "EXITNIHILO.AreaTypeCube",
        emanation: "EXITNIHILO.AreaTypeEmanation",
        line: "EXITNIHILO.AreaTypeLine",
        square: "EXITNIHILO.AreaTypeSquare",
    },

    areaSizes: {
        5: "EXITNIHILO.AreaSize5",
        10: "EXITNIHILO.AreaSize10",
        15: "EXITNIHILO.AreaSize15",
        20: "EXITNIHILO.AreaSize20",
        25: "EXITNIHILO.AreaSize25",
        30: "EXITNIHILO.AreaSize30",
        40: "EXITNIHILO.AreaSize40",
        45: "EXITNIHILO.AreaSize45",
        50: "EXITNIHILO.AreaSize50",
        60: "EXITNIHILO.AreaSize60",
        65: "EXITNIHILO.AreaSize65",
        75: "EXITNIHILO.AreaSize75",
        80: "EXITNIHILO.AreaSize80",
        90: "EXITNIHILO.AreaSize90",
        100: "EXITNIHILO.AreaSize100",
        120: "EXITNIHILO.AreaSize120",
        360: "EXITNIHILO.AreaSize360",
        500: "EXITNIHILO.AreaSize500",
        1000: "EXITNIHILO.AreaSize1000",
        1320: "EXITNIHILO.AreaSizeQuarterMile",
        5280: "EXITNIHILO.AreaSize1Mile",
    },

    attitude: {
        hostile: "EXITNIHILO.Attitudes.Hostile",
        unfriendly: "EXITNIHILO.Attitudes.Unfriendly",
        indifferent: "EXITNIHILO.Attitudes.Indifferent",
        friendly: "EXITNIHILO.Attitudes.Friendly",
        helpful: "EXITNIHILO.Attitudes.Helpful",
    },

    skillList: {
        acrobatics: "EXITNIHILO.SkillAcrobatics",
        arcana: "EXITNIHILO.SkillArcana",
        athletics: "EXITNIHILO.SkillAthletics",
        crafting: "EXITNIHILO.SkillCrafting",
        deception: "EXITNIHILO.SkillDeception",
        diplomacy: "EXITNIHILO.SkillDiplomacy",
        intimidation: "EXITNIHILO.SkillIntimidation",
        medicine: "EXITNIHILO.SkillMedicine",
        nature: "EXITNIHILO.SkillNature",
        occultism: "EXITNIHILO.SkillOccultism",
        performance: "EXITNIHILO.SkillPerformance",
        religion: "EXITNIHILO.SkillReligion",
        society: "EXITNIHILO.SkillSociety",
        stealth: "EXITNIHILO.SkillStealth",
        survival: "EXITNIHILO.SkillSurvival",
        thievery: "EXITNIHILO.SkillThievery",
        lore: "EXITNIHILO.SkillLore",
    },

    spellComponents: {
        V: "EXITNIHILO.SpellComponentV",
        S: "EXITNIHILO.SpellComponentS",
        M: "EXITNIHILO.SpellComponentM",
        F: "EXITNIHILO.SpellComponentF",
    },

    spellCategories: {
        spell: "EXITNIHILO.SpellCategorySpell",
        focus: "EXITNIHILO.SpellCategoryFocus",
        ritual: "EXITNIHILO.SpellCategoryRitual",
    },

    spellTypes: {
        attack: "EXITNIHILO.SpellTypeAttack",
        save: "EXITNIHILO.SpellTypeSave",
        heal: "EXITNIHILO.SpellTypeHeal",
        utility: "EXITNIHILO.SpellTypeUtility",
    },

    spellLevels: {
        1: "EXITNIHILO.SpellLevel1",
        2: "EXITNIHILO.SpellLevel2",
        3: "EXITNIHILO.SpellLevel3",
        4: "EXITNIHILO.SpellLevel4",
        5: "EXITNIHILO.SpellLevel5",
        6: "EXITNIHILO.SpellLevel6",
        7: "EXITNIHILO.SpellLevel7",
        8: "EXITNIHILO.SpellLevel8",
        9: "EXITNIHILO.SpellLevel9",
        10: "EXITNIHILO.SpellLevel10",
    }, // TODO: Compute levels!

    actionTypes: {
        action: "EXITNIHILO.ActionTypeAction",
        reaction: "EXITNIHILO.ActionTypeReaction",
        free: "EXITNIHILO.ActionTypeFree",
        passive: "EXITNIHILO.ActionTypePassive",
    },

    actionsNumber: {
        1: "EXITNIHILO.ActionNumber1",
        2: "EXITNIHILO.ActionNumber2",
        3: "EXITNIHILO.ActionNumber3",
    },

    actionCategories: {
        interaction: "EXITNIHILO.ActionCategoryInteraction",
        defensive: "EXITNIHILO.ActionCategoryDefensive",
        offensive: "EXITNIHILO.ActionCategoryOffensive",
    },

    frequencies: {
        PT1M: "EXITNIHILO.Duration.PT1M",
        PT10M: "EXITNIHILO.Duration.PT10M",
        PT1H: "EXITNIHILO.Duration.PT1H",
        PT24H: "EXITNIHILO.Duration.PT24H",
        day: "EXITNIHILO.Duration.day",
        P1W: "EXITNIHILO.Duration.P1W",
    },

    // Proficiency Multipliers
    proficiencyLevels: [
        "EXITNIHILO.ProficiencyLevel0", // untrained
        "EXITNIHILO.ProficiencyLevel1", // trained
        "EXITNIHILO.ProficiencyLevel2", // expert
        "EXITNIHILO.ProficiencyLevel3", // master
        "EXITNIHILO.ProficiencyLevel4", // legendary
    ] as const,

    speedTypes: {
        swim: "EXITNIHILO.SpeedTypesSwim",
        climb: "EXITNIHILO.SpeedTypesClimb",
        fly: "EXITNIHILO.SpeedTypesFly",
        burrow: "EXITNIHILO.SpeedTypesBurrow",
    },

    prerequisitePlaceholders: {
        prerequisite1: "EXITNIHILO.Prerequisite1",
        prerequisite2: "EXITNIHILO.Prerequisite2",
        prerequisite3: "EXITNIHILO.Prerequisite3",
        prerequisite4: "EXITNIHILO.Prerequisite4",
        prerequisite5: "EXITNIHILO.Prerequisite5",
    },

    bulkTypes: {
        L: "EXITNIHILO.BulkTypeLight",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
        17: "17",
        18: "18",
        19: "19",
        20: "20",
        21: "21",
        22: "22",
        23: "23",
        24: "24",
        25: "25",
        26: "26",
        27: "27",
        28: "28",
        29: "29",
        30: "30",
        31: "31",
        32: "32",
        33: "33",
        34: "34",
        35: "35",
        36: "36",
        37: "37",
        38: "38",
        39: "39",
        40: "40",
        41: "41",
        42: "42",
        43: "43",
        44: "44",
        45: "45",
        46: "46",
        47: "47",
        48: "48",
        49: "49",
        50: "50",
    },

    pfsFactions: {
        EA: "EXITNIHILO.PFS.Factions.EA",
        GA: "EXITNIHILO.PFS.Factions.GA",
        HH: "EXITNIHILO.PFS.Factions.HH",
        VS: "EXITNIHILO.PFS.Factions.VS",
        RO: "EXITNIHILO.PFS.Factions.RO",
        VW: "EXITNIHILO.PFS.Factions.VW",
    },

    pfsSchools: {
        none: "EXITNIHILO.PFS.School.None",
        scrolls: "EXITNIHILO.PFS.School.Scrolls",
        spells: "EXITNIHILO.PFS.School.Spells",
        swords: "EXITNIHILO.PFS.School.Swords",
    },

    // Languages, alphabetical by common, uncommon, secret
    languages: {
        common: "EXITNIHILO.LanguageCommon",
        draconic: "EXITNIHILO.LanguageDraconic",
        dwarven: "EXITNIHILO.LanguageDwarven",
        elven: "EXITNIHILO.LanguageElven",
        gnomish: "EXITNIHILO.LanguageGnomish",
        goblin: "EXITNIHILO.LanguageGoblin",
        halfling: "EXITNIHILO.LanguageHalfling",
        jotun: "EXITNIHILO.LanguageJotun",
        orcish: "EXITNIHILO.LanguageOrcish",
        sylvan: "EXITNIHILO.LanguageSylvan",
        undercommon: "EXITNIHILO.LanguageUndercommon",
        ysoki: "EXITNIHILO.LanguageYsoki",
        abyssal: "EXITNIHILO.LanguageAbyssal",
        adlet: "EXITNIHILO.LanguageAdlet",
        aklo: "EXITNIHILO.LanguageAklo",
        akitonian: "EXITNIHILO.LanguageAkitonian",
        alghollthu: "EXITNIHILO.LanguageAlghollthu",
        amurrun: "EXITNIHILO.LanguageAmurrun",
        anadi: "EXITNIHILO.LanguageAnadi",
        "ancient-osiriani": "EXITNIHILO.LanguageAncientOsiriani",
        anugobu: "EXITNIHILO.LanguageAnugobu",
        arcadian: "EXITNIHILO.LanguageArcadian",
        aquan: "EXITNIHILO.LanguageAquan",
        arboreal: "EXITNIHILO.LanguageArboreal",
        auran: "EXITNIHILO.LanguageAuran",
        boggard: "EXITNIHILO.LanguageBoggard",
        calda: "EXITNIHILO.LanguageCalda",
        caligni: "EXITNIHILO.LanguageCaligni",
        celestial: "EXITNIHILO.LanguageCelestial",
        cyclops: "EXITNIHILO.LanguageCyclops",
        daemonic: "EXITNIHILO.LanguageDaemonic",
        destrachan: "EXITNIHILO.LanguageDestrachan",
        drooni: "EXITNIHILO.LanguageDrooni",
        dziriak: "EXITNIHILO.LanguageDziriak",
        ekujae: "EXITNIHILO.LanguageEkujae",
        erutaki: "EXITNIHILO.LanguageErutaki",
        formian: "EXITNIHILO.LanguageFormian",
        garundi: "EXITNIHILO.LanguageGarundi",
        girtablilu: "EXITNIHILO.LanguageGirtablilu",
        gnoll: "EXITNIHILO.LanguageGnoll",
        goloma: "EXITNIHILO.LanguageGoloma",
        grippli: "EXITNIHILO.LanguageGrippli",
        hallit: "EXITNIHILO.LanguageHallit",
        hwan: "EXITNIHILO.LanguageHwan",
        iblydan: "EXITNIHILO.LanguageIblydan",
        ignan: "EXITNIHILO.LanguageIgnan",
        ikeshti: "EXITNIHILO.LanguageIkeshti",
        infernal: "EXITNIHILO.LanguageInfernal",
        iruxi: "EXITNIHILO.LanguageIruxi",
        jistkan: "EXITNIHILO.LanguageJistkan",
        jyoti: "EXITNIHILO.LanguageJyoti",
        kaava: "EXITNIHILO.LanguageKaava",
        kashrishi: "EXITNIHILO.LanguageKashrishi",
        kibwani: "EXITNIHILO.LanguageKibwani",
        kitsune: "EXITNIHILO.LanguageKitsune",
        kelish: "EXITNIHILO.LanguageKelish",
        lirgeni: "EXITNIHILO.LanguageLirgeni",
        mahwek: "EXITNIHILO.LanguageMahwek",
        minaten: "EXITNIHILO.LanguageMinaten",
        minkaian: "EXITNIHILO.LanguageMinkaian",
        mwangi: "EXITNIHILO.LanguageMwangi",
        mzunu: "EXITNIHILO.LanguageMzunu",
        nagaji: "EXITNIHILO.LanguageNagaji",
        necril: "EXITNIHILO.LanguageNecril",
        ocotan: "EXITNIHILO.LanguageOcotan",
        okaiyan: "EXITNIHILO.LanguageOkaiyan",
        osiriani: "EXITNIHILO.LanguageOsiriani",
        protean: "EXITNIHILO.LanguageProtean",
        rasu: "EXITNIHILO.LanguageRasu",
        ratajin: "EXITNIHILO.LanguageRatajin",
        razatlani: "EXITNIHILO.LanguageRazatlani",
        requian: "EXITNIHILO.LanguageRequian",
        russian: "EXITNIHILO.LanguageRussian",
        senzar: "EXITNIHILO.LanguageSenzar",
        shadowtongue: "EXITNIHILO.LanguageShadowtongue",
        shobhad: "EXITNIHILO.LanguageShobhad",
        shisk: "EXITNIHILO.LanguageShisk",
        shoanti: "EXITNIHILO.LanguageShoanti",
        shoony: "EXITNIHILO.LanguageShoony",
        skald: "EXITNIHILO.LanguageSkald",
        sphinx: "EXITNIHILO.LanguageSphinx",
        strix: "EXITNIHILO.LanguageStrix",
        taldane: "EXITNIHILO.LanguageTaldane",
        tekritanin: "EXITNIHILO.LanguageTekritanin",
        tengu: "EXITNIHILO.LanguageTengu",
        terran: "EXITNIHILO.LanguageTerran",
        thassilonian: "EXITNIHILO.LanguageThassilonian",
        tien: "EXITNIHILO.LanguageTien",
        utopian: "EXITNIHILO.LanguageUtopian",
        vanara: "EXITNIHILO.LanguageVanara",
        varisian: "EXITNIHILO.LanguageVarisian",
        varki: "EXITNIHILO.LanguageVarki",
        vishkanyan: "EXITNIHILO.LanguageVishkanyan",
        vudrani: "EXITNIHILO.LanguageVudrani",
        wyrwood: "EXITNIHILO.LanguageWyrwood",
        xanmba: "EXITNIHILO.LanguageXanmba",
        androffan: "EXITNIHILO.LanguageAndroffan",
        azlanti: "EXITNIHILO.LanguageAzlanti",
        grioth: "EXITNIHILO.LanguageGrioth",
        kovintal: "EXITNIHILO.LanguageKovintal",
        migo: "EXITNIHILO.LanguageMiGo",
        munavri: "EXITNIHILO.LanguageMunavri",
        samsaran: "EXITNIHILO.LanguageSamsaran",
        sasquatch: "EXITNIHILO.LanguageSasquatch",
        shae: "EXITNIHILO.LanguageShae",
        yithian: "EXITNIHILO.LanguageYithian",
        druidic: "EXITNIHILO.LanguageDruidic",
    },

    attackEffects: {
        grab: "EXITNIHILO.AttackEffectGrab",
        "improved-grab": "EXITNIHILO.AttackEffectImprovedGrab",
        constrict: "EXITNIHILO.AttackEffectConstrict",
        "greater-constrict": "EXITNIHILO.AttackEffectGreaterConstrict",
        knockdown: "EXITNIHILO.AttackEffectKnockdown",
        "improved-knockdown": "EXITNIHILO.AttackEffectImprovedKnockdown",
        push: "EXITNIHILO.AttackEffectPush",
        "improved-push": "EXITNIHILO.AttackEffectImprovedPush",
        trip: "EXITNIHILO.AttackEffectTrip",
    },

    // Year offsets relative to the current actual year
    worldClock: {
        AR: { yearOffset: 2700 },
        IC: { yearOffset: 5200 },
        AD: { yearOffset: -95 },
        CE: { yearOffset: 0 },
    },

    monsterAbilities: () => {
        return {
            "All-Around Vision": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>This monster can see in all directions simultaneously, and therefore can\'t be flanked.',
            },
            "Aquatic Ambush": {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br><b>Requirements</b> The monster is hiding in water and a creature that hasn\'t detected it is within the listed number of feet. <b>Effect</b> The monster moves up to its swim Speed + 10 feet toward the triggering creature, traveling on water and on land. Once the creature is in reach, the monster makes a Strike against it. The creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=16">flat-footed</a> against this Strike.',
            },
            "Attack of Opportunity": {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br><b>Trigger</b> A creature within the monster\'s reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using. <b>Effect</b> The monster attempts a melee Strike against the triggering creature. If the attack is a critical hit and the trigger was a manipulate action, the monster disrupts that action. This Strike doesn\'t count toward the monster\'s multiple attack penalty, and its multiple attack penalty doesn\'t apply to this Strike.',
            },
            "At-Will Spells": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>The monster can cast its at-will spells any number of times without using up spell slots.',
            },
            Aura: {
                actionType: "passive",
                actionCost: 1,
                description:
                    "<b>Source</b> <a href=\"https://paizo.com/products/btq01y0m?Pathfinder-Bestiary\" target=\"_blank\" class=\"external-link\"><i>Bestiary pg. 342</i></a><br>A monster's aura automatically affects everything within a specified emanation around that monster. The monster doesn't need to spend actions on the aura; rather, the aura's effects are applied at specific times, such as when a creature ends its turn in the aura or when creatures enter the aura.<br><br> If an aura does nothing but deal damage, its entry lists only the radius, damage, and saving throw. Such auras deal this damage to a creature when the creature enters the aura and when a creature starts its turn in the aura. A creature can take damage from the aura only once per round.<br><br> The GM might determine that a monster's aura doesn't affect its own allies. For example, a creature might be immune to a monster's frightful presence if they have been around each other for a long time.",
            },
            Buck: {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>Most monsters that serve as mounts can attempt to\nbuck off unwanted or annoying riders, but most mounts\nwill not use this reaction against a trusted creature unless\nthe mounts are spooked or mistreated. <b>Trigger</b> A creature\nMounts or uses the Command an Animal action while riding\nthe monster. <b>Effect</b> The triggering creature must succeed\nat a Reflex saving throw against the listed DC or fall off the\ncreature and land prone. If the save is a critical failure, the\ntriggering creature also takes 1d6 bludgeoning damage in\naddition to the normal damage for the fall.',
            },
            "Catch Rock": {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br><b>Requirements</b> The monster must have a free hand but can Release anything it\'s holding as part of this reaction. <b>Trigger</b> The monster is targeted with a thrown rock Strike or a rock would fall on the monster. <b>Effect</b> The monster gains a +4 circumstance bonus to its AC against the triggering attack or to any defense against the falling rock. If the attack misses or the monster successfully defends against the falling rock, the monster catches the rock, takes no damage, and is now holding the rock.',
            },
            "Change Shape": {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>(<a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=32">concentrate</a>, [magical tradition], <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=127">polymorph</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=157">transmutation</a>) The monster changes its shape indefinitely. It can use this action again to return to its natural shape or adopt a new shape. Unless otherwise noted, a monster cannot use Change Shape to appear as a specific individual. Using Change Shape counts as creating a disguise for the Impersonate use of Deception. The monster\'s transformation automatically defeats Perception DCs to determine whether the creature is a member of the ancestry or creature type into which it transformed, and it gains a +4 status bonus to its Deception DC to prevent others from seeing through its disguise. Change Shape abilities specify what shapes the monster can adopt. The monster doesn\'t gain any special abilities of the new shape, only its physical form. For example, in each shape, it replaces its normal Speeds and Strikes, and might potentially change its senses or size. Any changes are listed in its stat block.',
            },
            "Constant Spells": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>A constant spell affects the monster without the monster needing to cast it, and its duration is unlimited. If a constant spell gets counteracted, the monster can reactivate it by spending the normal spellcasting actions the spell\u001crequires.',
            },
            Constrict: {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>The monster deals the listed amount of damage to any number of creatures grabbed or restrained by it. Each of those creatures can attempt a basic Fortitude save with the listed DC.',
            },
            Coven: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 342</i></a><br>(<a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=47">divination</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=106">mental</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=120">occult</a>) This monster can form a coven with two or more other creatures who also have the coven ability. This involves performing an 8-hour ceremony with all prospective coven members. After the coven is formed, each of its members gains elite adjustments (page 6), adjusting their levels accordingly. Coven members can sense other members\' locations and conditions by spending a single action, which has the concentrate trait, and can sense what another coven member is sensing as a two-action activity, which has the concentrate trait as well.<br><br> Covens also grant spells and rituals to their members, but these can be cast only in cooperation between three coven members who are all within 30 feet of one another. A coven member can contribute to a coven spell with a single-action spellcasting activity that has a single verbal component. If two coven members have contributed these actions within the last round, a third member can cast a coven spell on her turn by spending the normal spellcasting actions. A coven can cast its coven spells an unlimited number of times but can cast only one coven spell each round. All covens grant the 8th-level <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=17">baleful polymorph</a></i> spell and all the following spells, which the coven can cast at any level up to 5th: <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=15">augury</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=34">charm</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=39">clairaudience</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=40">clairvoyance</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=90">dream message</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=159">illusory disguise</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=161">illusory scene</a></i>, <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=239">prying eye</a></i>, and <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=329">talking corpse</a></i>. Individual creatures with the coven ability also grant additional spells to any coven they join. A coven can also cast the <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Rituals.aspx?ID=9">control weather</a></i> ritual, with a DC of 23 instead of the standard DC.<br><br> If a coven member leaving the coven or the death of a coven member brings the coven below three members, the remaining members keep their elite adjustments for 24 hours, but without enough members to contribute the necessary actions, they can\'t cast coven spells.',
            },
            Darkvision: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>A monster with darkvision can see perfectly well in areas of darkness and dim light, though such vision is in black and white only. Some forms of magical darkness, such as a 4th-level <i><a style="text-decoration:underline" href="https://2e.aonprd.com/Spells.aspx?ID=59">darkness</a></i> spell, block normal darkvision. A monster with greater darkvision, however, can see through even these forms of magical darkness.',
            },
            Disease: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>When a creature is exposed to a monster\'s disease, it attempts a Fortitude save or succumbs to the disease. The level of a disease is the level of the monster in\u001f icting the disease. The disease follows the <a style="text-decoration:underline" href="https://2e.aonprd.com/Rules.aspx?ID=361">rules for afflictions</a>.',
            },
            Engulf: {
                actionType: "action",
                actionCost: 2,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster Strides up to double its Speed and can move through the spaces of any creatures in its path. Any creature of the monster\'s size or smaller whose space the monster moves through can attempt a Reflex save with the listed DC to avoid being engulfed. A creature unable to act automatically critically fails this save. If a creature succeeds at its save, it can choose to be either pushed aside (out of the monster\'s path) or pushed in front of the monster to the end of the monster\'s movement. The monster can attempt to Engulf the same creature only once in a single use of Engulf. The monster can contain as many creatures as can fit in its space.<br><br> A creature that fails its save is pulled into the monster\'s body. It is grabbed, is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=35">slowed 1</a>, and has to hold its breath or start suffocating. The creature takes the listed amount of damage when first engulfed and at the end of each of its turns while it\'s engulfed. An engulfed creature can get free by Escaping against the listed escape DC. An engulfed creature can attack the monster engulfing it, but only with unarmed attacks or with weapons of light Bulk or less. The engulfing creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=16">flat-footed</a> against the attack. If the monster takes piercing or slashing damage equaling or exceeding the listed Rupture value from a single attack or spell, the engulfed creature cuts itself free. A creature that gets free by either method can immediately breathe and exits the swallowing monster\'s space.<br><br> If the monster dies, all creatures it has engulfed are automatically released as the monster\'s form loses cohesion.',
            },
            "Fast Healing": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>A monster with this ability regains the given number of Hit Points each round at the beginning of its turn.',
            },
            Ferocity: {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br><b>Trigger</b> The monster is reduced to 0 HP. <b>Effect</b> The monster avoids being knocked out and remains at 1 HP, but its <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=42">wounded</a> value increases by 1. When it is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=42">wounded 3</a>, it can no longer use this ability.',
            },
            "Frightful Presence": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>(<a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=206">aura</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=60">emotion</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=68">fear</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=106">mental</a>) A creature that first enters the area must attempt a Will save. Regardless of the result of the saving throw, the creature is temporarily immune to this monster\'s Frightful Presence for 1 minute.<br><br> <b>Critical Success</b> The creature is unaffected by the presence.<br> <b>Success</b> The creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=19">frightened 1</a>.<br> <b>Failure</b> The creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=19">frightened 2</a>.<br> <b>Critical Failure</b> The creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=19">frightened 4</a>.',
            },
            Grab: {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br><b>Requirements</b> The monster\'s last action was a success with a Strike that lists Grab in its damage entry, or it has a creature grabbed using this action. <b>Effect</b> The monster automatically Grabs the target until the end of the monster\'s next turn. The creature is grabbed by whichever body part the monster attacked with, and that body part can\'t be used to Strike creatures until the grab is ended.<br><br> Using Grab extends the duration of the monster\'s Grab until the end of its next turn for all creatures grabbed by it. A grabbed creature can use the <a style="text-decoration:underline" href="https://2e.aonprd.com/Actions.aspx?ID=79">Escape</a> action to get out of the grab, and the Grab ends for a grabbed creatures if the monster moves away from it.',
            },
            "Greater Constrict": {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster deals the listed amount of damage to any number of creatures grabbed or restrained by it. Each of those creatures can attempt a basic Fortitude save with the listed DC. A creature that fails this save falls <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=38">unconscious</a>, and a creature that succeeds is then temporarily immune to falling <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=38">unconscious</a> from Greater Constrict for 1 minute.',
            },
            "Improved Grab": {
                actionType: "free",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster can use Grab as a free action triggered by a hit with its initial attack. A monster with Improved Grab still needs to spend an action to extend the duration for creatures it already has grabbed.',
            },
            "Improved Knockdown": {
                actionType: "free",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster can use Knockdown as a free action triggered by a hit with its initial attack.',
            },
            "Improved Push": {
                actionType: "free",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster can use Push as a free action triggered by a hit with its initial attack.',
            },
            Knockdown: {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br><b>Requirements</b> The monster\'s last action was a success with a Strike that lists Knockdown in its damage entry. <b>Effect</b> The monster knocks the target prone.',
            },
            Lifesense: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>Lifesense allows a monster to sense the vital essence of living and undead creatures within the listed range. The sense can distinguish between the positive energy animating living creatures and the negative energy animating undead creatures, much as sight distinguishes colors.',
            },
            "Light Blindness": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>When first exposed to bright light, the monster is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=1">blinded</a> until the end of its next turn. After this exposure, light doesn\'t blind the monster again until after it spends 1 hour in darkness. However, as long as the monster is in an area of bright light, it\'s <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=7">dazzled</a>.',
            },
            "Low-Light Vision": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>The monster can see in dim light as though it were bright light, so it ignores the <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=4">concealed</a> condition due to dim light.',
            },
            Poison: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>When a creature is exposed to a monster\'s poison, it attempts a Fortitude save to avoid becoming poisoned. The level of a poison is the level of the monster inflicting the poison. The poison follows the <a style="text-decoration:underline" href="https://2e.aonprd.com/Rules.aspx?ID=361">rules for afflictions</a>.',
            },
            Push: {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br><b>Requirements</b> The monster\'s last action was a success with a Strike that lists Push in its damage entry. <b>Effect</b> The monster automatically knocks the target away from the monster. Unless otherwise noted in the ability description, the creature is pushed 5 feet. If the attack was a critical hit, this distance is doubled.',
            },
            Regeneration: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 343</i></a><br>This monster regains the listed number of Hit Points each round at the beginning of its turn. Its <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=11">dying</a> condition never increases beyond <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=11">dying 3</a> as long as its regeneration is active. However, if it takes damage of a type listed in the regeneration entry, its regeneration deactivates until the end of its next turn. Deactivate the regeneration before applying any damage of a listed type, since that damage might kill the monster by bringing it to <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=11">dying 4</a>.',
            },
            Rend: {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>A Rend entry lists a Strike the monster has. <b>Requirements</b> The monster hit the same enemy with two consecutive Strikes of the listed type in the same round. <b>Effect</b> The monster automatically deals that Strike\'s damage again to the enemy.',
            },
            "Retributive Strike": {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br><b>Trigger</b> An enemy damages the monster\'s ally, and both are within 15 feet of the monster. <b>Effect</b> The ally gains resistance to all damage against the triggering damage equal to 2 + the monster\'s level. If the foe is within reach, the monster makes a melee Strike against it.',
            },
            Scent: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>Scent involves sensing creatures or objects by smell, and is usually a vague sense. The range is listed in the ability, and it functions only if the creature or object being detected emits an aroma (for instance, incorporeal creatures usually do not exude an aroma).<br><br> If a creature emits a heavy aroma or is upwind, the GM can double or even triple the range of scent abilities used to detect that creature, and the GM can reduce the range if a creature is downwind.',
            },
            "Shield Block": {
                actionType: "reaction",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br><b>Trigger</b> The monster has its shield raised and takes damage from a physical attack. <b>Effect</b> The monster snaps its shield into place to deflect a blow. The shield prevents the monster from taking an amount of damage up to the shield\'s Hardness. The monster and the shield each take any remaining damage, possibly breaking or destroying the shield.',
            },
            "Sneak Attack": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>When the monster Strikes a creature that has the <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=16">flat-footed</a> condition with an <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=170">agile</a> or <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=179">finesse</a> melee weapon, an <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=170">agile</a> or <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=179">finesse</a> unarmed attack, or a ranged weapon attack, it also deals the listed precision damage. For a ranged attack with a thrown weapon, that weapon must also be an <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=170">agile</a> or <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=179">finesse</a> weapon.',
            },
            "Swallow Whole": {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>(<a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=15">attack</a>) The monster attempts to swallow a creature of the listed size or smaller that it has grabbed in its jaws or mouth. If a swallowed creature is of the maximum size listed, the monster can\'t use Swallow Whole again. If the creature is smaller than the maximum, the monster can usually swallow more creatures; the GM determines the maximum. The monster attempts an <a style="text-decoration:underline" href="https://2e.aonprd.com/Skills.aspx?ID=3">Athletics</a> check opposed by the grabbed creature\'s Reflex DC. If it succeeds, it swallows the creature. The monster\'s mouth or jaws no longer grab a creature it has swallowed, so the monster is free to use them to Strike or Grab once again. The monster can\'t attack creatures it has swallowed.<br><br> A swallowed creature is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=20">grabbed</a>, is <a style="text-decoration:underline" href="https://2e.aonprd.com/Conditions.aspx?ID=35">slowed 1</a>, and has to hold its breath or start suffocating. The swallowed creature takes the listed amount of damage when first swallowed and at the end of each of its turns while it\'s swallowed. If the victim Escapes this ability\'s grabbed condition, it exits through the monster\'s mouth. This frees any other creature grabbed in the monster\'s mouth or jaws. A swallowed creature can attack the monster that has swallowed it, but only with unarmed attacks or with weapons of light Bulk or less. The engulfing creature is flat-footed against the attack. If the monster takes piercing or slashing damage equaling or exceeding the listed Rupture value from a single attack or spell, the engulfed creature cuts itself free. A creature that gets free by either Escaping or cutting itself free can immediately breathe and exits the swallowing monster\'s space.<br><br> If the monster dies, a swallowed creature can be freed by creatures adjacent to the corpse if they spend a combined total of 3 actions cutting the monster open with a weapon or unarmed attack that deals piercing or slashing damage.',
            },
            "Swarm Mind": {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>This monster doesn\'t have a single mind (typically because it\'s a swarm of smaller creatures), and is immune to mental effects that target only a specific number of creatures. It is still subject to mental effects that affect all creatures in an area.',
            },
            Telepathy: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>(<a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=206">aura</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=47">divination</a>, <a style="text-decoration:underline" href="https://2e.aonprd.com/Traits.aspx?ID=103">magical</a>) A monster with telepathy can communicate mentally with any creatures within the listed radius, as long as they share a language. This doesn\'t give any special access to their thoughts, and communicates no more information than normal speech would.',
            },
            "Throw Rock": {
                actionType: "action",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>The monster picks up a rock within reach or retrieves a stowed rock and throws it, making a ranged Strike.',
            },
            Trample: {
                actionType: "action",
                actionCost: 3,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>The monster Strides up to double its Speed and can move through the spaces of creatures of the listed size, Trampling each creature whose space it enters. The monster can attempt to Trample the same creature only once in a single use of Trample. The monster deals the damage of the listed Strike, but trampled creatures can attempt a basic Reflex save at the listed DC (no damage on a critical success, half damage on a success, double damage on a critical failure).',
            },
            Tremorsense: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>Tremorsense allows a monster to feel the vibrations through a solid surface caused by movement. It is an imprecise sense with a limited range (listed in the ability). Tremorsense functions only if the monster is on the same surface as the subject, and only if the subject is moving along (or burrowing through) the surface.',
            },
            Wavesense: {
                actionType: "passive",
                actionCost: 1,
                description:
                    '<b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 344</i></a><br>This sense allows a monster to feel vibrations caused by movement through a liquid. It\'s an imprecise sense with a limited range (listed in the ability). Wavesense functions only if monster and the subject are in the same body of liquid, and only if the subject is moving through the liquid.',
            },
        };
    },

    SETTINGS: {
        automation: {
            rulesBasedVision: {
                name: "EXITNIHILO.SETTINGS.Automation.RulesBasedVision.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.RulesBasedVision.Hint",
            },
            effectExpiration: {
                name: "EXITNIHILO.SETTINGS.Automation.EffectExpiration.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.EffectExpiration.Hint",
            },
            removeExpiredEffects: {
                name: "EXITNIHILO.SETTINGS.Automation.RemoveExpiredEffects.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.RemoveExpiredEffects.Hint",
            },
            flankingDetection: {
                name: "EXITNIHILO.SETTINGS.Automation.FlankingDetection.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.FlankingDetection.Hint",
            },
            actorsDeadAtZero: {
                name: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.Hint",
                neither: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.Neither",
                npcsOnly: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.NPCsOnly",
                pcsOnly: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.PCsOnly",
                both: "EXITNIHILO.SETTINGS.Automation.ActorsDeadAtZero.Both",
            },
            lootableNPCs: {
                name: "EXITNIHILO.SETTINGS.Automation.LootableNPCs.Name",
                hint: "EXITNIHILO.SETTINGS.Automation.LootableNPCs.Hint",
            },
        },
        homebrew: {
            creatureTraits: {
                name: "EXITNIHILO.SETTINGS.Homebrew.CreatureTraits.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.CreatureTraits.Hint",
            },
            featTraits: {
                name: "EXITNIHILO.SETTINGS.Homebrew.FeatTraits.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.FeatTraits.Hint",
            },
            languages: {
                name: "EXITNIHILO.SETTINGS.Homebrew.Languages.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.Languages.Hint",
            },
            magicSchools: {
                name: "EXITNIHILO.SETTINGS.Homebrew.MagicSchools.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.MagicSchools.Hint",
            },
            spellTraits: {
                name: "EXITNIHILO.SETTINGS.Homebrew.SpellTraits.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.SpellTraits.Hint",
            },
            weaponCategories: {
                name: "EXITNIHILO.SETTINGS.Homebrew.WeaponCategories.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.WeaponCategories.Hint",
            },
            weaponGroups: {
                name: "EXITNIHILO.SETTINGS.Homebrew.WeaponGroups.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.WeaponGroups.Hint",
            },
            baseWeapons: {
                name: "EXITNIHILO.SETTINGS.Homebrew.BaseWeapons.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.BaseWeapons.Hint",
            },
            weaponTraits: {
                name: "EXITNIHILO.SETTINGS.Homebrew.WeaponTraits.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.WeaponTraits.Hint",
            },
            equipmentTraits: {
                name: "EXITNIHILO.SETTINGS.Homebrew.EquipmentTraits.Name",
                hint: "EXITNIHILO.SETTINGS.Homebrew.EquipmentTraits.Hint",
            },
        },
        worldClock: {
            name: "EXITNIHILO.SETTINGS.WorldClock.Name",
            label: "EXITNIHILO.SETTINGS.WorldClock.Label",
            hint: "EXITNIHILO.SETTINGS.WorldClock.Hint",
            dateTheme: {
                name: "EXITNIHILO.SETTINGS.WorldClock.DateTheme.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.DateTheme.Hint",
                AR: "EXITNIHILO.SETTINGS.WorldClock.DateTheme.AR",
                AD: "EXITNIHILO.SETTINGS.WorldClock.DateTheme.AD",
                CE: "EXITNIHILO.SETTINGS.WorldClock.DateTheme.CE",
            },
            timeConvention: {
                name: "EXITNIHILO.SETTINGS.WorldClock.TimeConvention.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.TimeConvention.Hint",
                twentyFour: "EXITNIHILO.SETTINGS.WorldClock.TimeConvention.TwentyFour",
                twelve: "EXITNIHILO.SETTINGS.WorldClock.TimeConvention.Twelve",
            },
            showClockButton: {
                name: "EXITNIHILO.SETTINGS.WorldClock.ShowClockButton.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.ShowClockButton.Hint",
            },
            playersCanView: {
                name: "EXITNIHILO.SETTINGS.WorldClock.PlayersCanView.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.PlayersCanView.Hint",
            },
            syncDarkness: {
                name: "EXITNIHILO.SETTINGS.WorldClock.SyncDarkness.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.SyncDarkness.Hint",
            },
            syncDarknessScene: {
                name: "EXITNIHILO.SETTINGS.WorldClock.SyncDarknessScene.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.SyncDarknessScene.Hint",
                enabled: "EXITNIHILO.SETTINGS.WorldClock.SyncDarknessScene.Enabled",
                disabled: "EXITNIHILO.SETTINGS.WorldClock.SyncDarknessScene.Disabled",
                default: "EXITNIHILO.SETTINGS.WorldClock.SyncDarknessScene.Default",
            },
            worldCreatedOn: {
                name: "EXITNIHILO.SETTINGS.WorldClock.WorldCreatedOn.Name",
                hint: "EXITNIHILO.SETTINGS.WorldClock.WorldCreatedOn.Hint",
            },
        },
        CampaignFeats: {
            name: "EXITNIHILO.SETTINGS.CampaignFeats.Name",
            hint: "EXITNIHILO.SETTINGS.CampaignFeats.Hint",
        },
    },

    Actor: {
        documentClasses: {
            character: CharacterExitNihilo,
        },
    },

    Item: {
        documentClasses: {
            armor: ArmorExitNihilo,
            backpack: ContainerExitNihilo,
            condition: ConditionExitNihilo,
            equipment: EquipmentExitNihilo,
            weapon: WeaponExitNihilo,
        },
        traits: {
            action: actionTraits,
            armor: armorTraits,
            ancestry: creatureTraits,
            backpack: equipmentTraits,
            book: equipmentTraits,
            consumable: consumableTraits,
            equipment: equipmentTraits,
            weapon: weaponTraits,            
        },
    },

    JournalEntry: { sheetClass: JournalSheetExitNihilo },

    Canvas: {
        darkness: {
            default: CONFIG.Canvas.darknessColor,
            gmVision: 0x76739e,
        },
    },
};
