// Ancestry and heritage traits
const ancestryTraits = {
    "half-elf": "EXITNIHILO.TraitHalfElf",
    "half-orc": "EXITNIHILO.TraitHalfOrc",
    aasimar: "EXITNIHILO.TraitAasimar",
    aberration: "EXITNIHILO.TraitAberration",
    anadi: "EXITNIHILO.TraitAnadi",
    android: "EXITNIHILO.TraitAndroid",
    aphorite: "EXITNIHILO.TraitAphorite",
    automaton: "EXITNIHILO.TraitAutomaton",
    azarketi: "EXITNIHILO.TraitAzarketi",
    beastkin: "EXITNIHILO.TraitBeastkin",
    catfolk: "EXITNIHILO.TraitCatfolk",
    changeling: "EXITNIHILO.TraitChangeling",
    conrasu: "EXITNIHILO.TraitConrasu",
    dhampir: "EXITNIHILO.TraitDhampir",
    duskwalker: "EXITNIHILO.TraitDuskwalker",
    dwarf: "EXITNIHILO.TraitDwarf",
    elf: "EXITNIHILO.TraitElf",
    fetchling: "EXITNIHILO.TraitFetchling",
    fleshwarp: "EXITNIHILO.TraitFleshwarp",
    ganzi: "EXITNIHILO.TraitGanzi",
    geniekin: "EXITNIHILO.TraitGeniekin",
    ghoran: "EXITNIHILO.TraitGhoran",
    gnoll: "EXITNIHILO.TraitGnoll",
    gnome: "EXITNIHILO.TraitGnome",
    goblin: "EXITNIHILO.TraitGoblin",
    goloma: "EXITNIHILO.TraitGoloma",
    grippli: "EXITNIHILO.TraitGrippli",
    halfling: "EXITNIHILO.TraitHalfling",
    hobgoblin: "EXITNIHILO.TraitHobgoblin",
    human: "EXITNIHILO.TraitHuman",
    ifrit: "EXITNIHILO.TraitIfrit",
    kashrishi: "EXITNIHILO.TraitKashrishi",
    kitsune: "EXITNIHILO.TraitKitsune",
    kobold: "EXITNIHILO.TraitKobold",
    leshy: "EXITNIHILO.TraitLeshy",
    lizardfolk: "EXITNIHILO.TraitLizardfolk",
    nagaji: "EXITNIHILO.TraitNagaji",
    orc: "EXITNIHILO.TraitOrc",
    oread: "EXITNIHILO.TraitOread",
    poppet: "EXITNIHILO.TraitPoppet",
    ratfolk: "EXITNIHILO.TraitRatfolk",
    shisk: "EXITNIHILO.TraitShisk",
    shoony: "EXITNIHILO.TraitShoony",
    skeleton: "EXITNIHILO.TraitSkeleton",
    sprite: "EXITNIHILO.TraitSprite",
    strix: "EXITNIHILO.TraitStrix",
    suli: "EXITNIHILO.TraitSuli",
    sylph: "EXITNIHILO.TraitSylph",
    tengu: "EXITNIHILO.TraitTengu",
    tiefling: "EXITNIHILO.TraitTiefling",
    undine: "EXITNIHILO.TraitUndine",
    vanara: "EXITNIHILO.TraitVanara",
    vishkanya: "EXITNIHILO.TraitVishkanya",
};

// Secondary traits of ancestries and heritages
const ancestryItemTraits = {
    ...ancestryTraits,
    amphibious: "EXITNIHILO.TraitAmphibious",
    fey: "EXITNIHILO.TraitFey",
    fungus: "EXITNIHILO.TraitFungus",
    humanoid: "EXITNIHILO.TraitHumanoid",
    plant: "EXITNIHILO.TraitPlant",
};

const elementalTraits = {
    air: "EXITNIHILO.TraitAir",
    earth: "EXITNIHILO.TraitEarth",
    fire: "EXITNIHILO.TraitFire",
    metal: "EXITNIHILO.TraitMetal",
    water: "EXITNIHILO.TraitWater",
};

const energyDamageTypes = {
    acid: "EXITNIHILO.TraitAcid",
    cold: "EXITNIHILO.TraitCold",
    electricity: "EXITNIHILO.TraitElectricity",
    fire: "EXITNIHILO.TraitFire",
    force: "EXITNIHILO.TraitForce",
    negative: "EXITNIHILO.TraitNegative",
    positive: "EXITNIHILO.TraitPositive",
    sonic: "EXITNIHILO.TraitSonic",
};

const creatureTraits = {
    ...ancestryItemTraits,
    ...elementalTraits,
    ...energyDamageTypes,
    aberration: "EXITNIHILO.TraitAberration",
    aeon: "EXITNIHILO.TraitAeon",
    aesir: "EXITNIHILO.TraitAesir",
    agathion: "EXITNIHILO.TraitAgathion",
    alchemical: "EXITNIHILO.TraitAlchemical",
    angel: "EXITNIHILO.TraitAngel",
    animal: "EXITNIHILO.TraitAnimal",
    anugobu: "EXITNIHILO.TraitAnugobu",
    aquatic: "EXITNIHILO.TraitAquatic",
    archon: "EXITNIHILO.TraitArchon",
    astral: "EXITNIHILO.TraitAstral",
    asura: "EXITNIHILO.TraitAsura",
    azata: "EXITNIHILO.TraitAzata",
    beast: "EXITNIHILO.TraitBeast",
    boggard: "EXITNIHILO.TraitBoggard",
    caligni: "EXITNIHILO.TraitCaligni",
    celestial: "EXITNIHILO.TraitCelestial",
    "charau-ka": "EXITNIHILO.TraitCharauKa",
    clockwork: "EXITNIHILO.TraitClockwork",
    construct: "EXITNIHILO.TraitConstruct",
    couatl: "EXITNIHILO.TraitCouatl",
    daemon: "EXITNIHILO.TraitDaemon",
    darvakka: "EXITNIHILO.TraitDarvakka",
    demon: "EXITNIHILO.TraitDemon",
    dero: "EXITNIHILO.TraitDero",
    devil: "EXITNIHILO.TraitDevil",
    dinosaur: "EXITNIHILO.TraitDinosaur",
    div: "EXITNIHILO.TraitDiv",
    dragon: "EXITNIHILO.TraitDragon",
    dream: "EXITNIHILO.TraitDream",
    drow: "EXITNIHILO.TraitDrow",
    duergar: "EXITNIHILO.TraitDuergar",
    duskwalker: "EXITNIHILO.TraitDuskwalker",
    eidolon: "EXITNIHILO.TraitEidolon",
    elemental: "EXITNIHILO.TraitElemental",
    ethereal: "EXITNIHILO.TraitEthereal",
    evocation: "EXITNIHILO.TraitEvocation",
    fiend: "EXITNIHILO.TraitFiend",
    formian: "EXITNIHILO.TraitFormian",
    fungus: "EXITNIHILO.TraitFungus",
    genie: "EXITNIHILO.TraitGenie",
    ghoran: "EXITNIHILO.TraitGhoran",
    ghost: "EXITNIHILO.TraitGhost",
    ghoul: "EXITNIHILO.TraitGhoul",
    ghul: "EXITNIHILO.TraitGhul",
    giant: "EXITNIHILO.TraitGiant",
    golem: "EXITNIHILO.TraitGolem",
    gremlin: "EXITNIHILO.TraitGremlin",
    grioth: "EXITNIHILO.TraitGrioth",
    grippli: "EXITNIHILO.TraitGrippli",
    hag: "EXITNIHILO.TraitHag",
    hantu: "EXITNIHILO.TraitHantu",
    herald: "EXITNIHILO.TraitHerald",
    humanoid: "EXITNIHILO.TraitHumanoid",
    ifrit: "EXITNIHILO.TraitIfrit",
    ikeshti: "EXITNIHILO.TraitIkeshti",
    illusion: "EXITNIHILO.TraitIllusion",
    incorporeal: "EXITNIHILO.TraitIncorporeal",
    inevitable: "EXITNIHILO.TraitInevitable",
    kami: "EXITNIHILO.TraitKami",
    kovintus: "EXITNIHILO.TraitKovintus",
    light: "EXITNIHILO.TraitLight",
    locathah: "EXITNIHILO.TraitLocathah",
    mental: "EXITNIHILO.TraitMental",
    merfolk: "EXITNIHILO.TraitMerfolk",
    mindless: "EXITNIHILO.TraitMindless",
    minion: "EXITNIHILO.TraitMinion",
    monitor: "EXITNIHILO.TraitMonitor",
    morlock: "EXITNIHILO.TraitMorlock",
    mortic: "EXITNIHILO.TraitMortic",
    mummy: "EXITNIHILO.TraitMummy",
    munavri: "EXITNIHILO.TraitMunavri",
    mutant: "EXITNIHILO.TraitMutant",
    nagaji: "EXITNIHILO.TraitNagaji",
    nymph: "EXITNIHILO.TraitNymph",
    oni: "EXITNIHILO.TraitOni",
    ooze: "EXITNIHILO.TraitOoze",
    orc: "EXITNIHILO.TraitOrc",
    oread: "EXITNIHILO.TraitOread",
    paaridar: "EXITNIHILO.TraitPaaridar",
    petitioner: "EXITNIHILO.TraitPetitioner",
    phantom: "EXITNIHILO.TraitPhantom",
    protean: "EXITNIHILO.TraitProtean",
    psychopomp: "EXITNIHILO.TraitPsychopomp",
    qlippoth: "EXITNIHILO.TraitQlippoth",
    rakshasa: "EXITNIHILO.TraitRakshasa",
    reflection: "EXITNIHILO.TraitReflection",
    sahkil: "EXITNIHILO.TraitSahkil",
    samsaran: "EXITNIHILO.TraitSamsaran",
    "sea-devil": "EXITNIHILO.TraitSeaDevil",
    serpentfolk: "EXITNIHILO.TraitSerpentfolk",
    seugathi: "EXITNIHILO.TraitSeugathi",
    shabti: "EXITNIHILO.TraitShabti",
    shadow: "EXITNIHILO.TraitShadow",
    shobhad: "EXITNIHILO.TraitShobhad",
    siktempora: "EXITNIHILO.TraitSiktempora",
    skeleton: "EXITNIHILO.TraitSkeleton",
    skelm: "EXITNIHILO.TraitSkelm",
    skulk: "EXITNIHILO.TraitSkulk",
    soulbound: "EXITNIHILO.TraitSoulbound",
    spirit: "EXITNIHILO.TraitSpirit",
    spriggan: "EXITNIHILO.TraitSpriggan",
    stheno: "EXITNIHILO.TraitStheno",
    summoned: "EXITNIHILO.TraitSummoned",
    swarm: "EXITNIHILO.TraitSwarm",
    sylph: "EXITNIHILO.TraitSylph",
    tane: "EXITNIHILO.TraitTane",
    tanggal: "EXITNIHILO.TraitTanggal",
    tengu: "EXITNIHILO.TraitTengu",
    time: "EXITNIHILO.TraitTime",
    titan: "EXITNIHILO.TraitTitan",
    troll: "EXITNIHILO.TraitTroll",
    troop: "EXITNIHILO.TraitTroop",
    undead: "EXITNIHILO.TraitUndead",
    undine: "EXITNIHILO.TraitUndine",
    urdefhan: "EXITNIHILO.TraitUrdefhan",
    vampire: "EXITNIHILO.TraitVampire",
    vanara: "EXITNIHILO.TraitVanara",
    velstrac: "EXITNIHILO.TraitVelstrac",
    vishkanya: "EXITNIHILO.TraitVishkanya",
    wayang: "EXITNIHILO.TraitWayang",
    werecreature: "EXITNIHILO.TraitWerecreature",
    wight: "EXITNIHILO.TraitWight",
    "wild-hunt": "EXITNIHILO.TraitWildHunt",
    wraith: "EXITNIHILO.TraitWraith",
    wyrwood: "EXITNIHILO.TraitWyrwood",
    xulgath: "EXITNIHILO.TraitXulgath",
    zombie: "EXITNIHILO.TraitZombie",
};

const spellOtherTraits = {
    amp: "EXITNIHILO.TraitAmp",
    attack: "EXITNIHILO.TraitAttack",
    auditory: "EXITNIHILO.TraitAuditory",
    aura: "EXITNIHILO.TraitAura",
    beast: "EXITNIHILO.TraitBeast",
    cantrip: "EXITNIHILO.TraitCantrip",
    composition: "EXITNIHILO.TraitComposition",
    concentrate: "EXITNIHILO.TraitConcentrate",
    consecration: "EXITNIHILO.TraitConsecration",
    contingency: "EXITNIHILO.TraitContingency",
    curse: "EXITNIHILO.TraitCurse",
    cursebound: "EXITNIHILO.TraitCursebound",
    darkness: "EXITNIHILO.TraitDarkness",
    death: "EXITNIHILO.TraitDeath",
    detection: "EXITNIHILO.TraitDetection",
    disease: "EXITNIHILO.TraitDisease",
    dream: "EXITNIHILO.TraitDream",
    eidolon: "EXITNIHILO.TraitEidolon",
    emotion: "EXITNIHILO.TraitEmotion",
    extradimensional: "EXITNIHILO.TraitExtradimensional",
    fear: "EXITNIHILO.TraitFear",
    fortune: "EXITNIHILO.TraitFortune",
    fungus: "EXITNIHILO.TraitFungus",
    healing: "EXITNIHILO.TraitHealing",
    hex: "EXITNIHILO.TraitHex",
    incapacitation: "EXITNIHILO.TraitIncapacitation",
    incarnate: "EXITNIHILO.TraitIncarnate",
    incorporeal: "EXITNIHILO.TraitIncorporeal",
    inhaled: "EXITNIHILO.TraitInhaled",
    light: "EXITNIHILO.TraitLight",
    linguistic: "EXITNIHILO.TraitLinguistic",
    litany: "EXITNIHILO.TraitLitany",
    metamagic: "EXITNIHILO.TraitMetamagic",
    mindless: "EXITNIHILO.TraitMindless",
    misfortune: "EXITNIHILO.TraitMisfortune",
    morph: "EXITNIHILO.TraitMorph",
    move: "EXITNIHILO.TraitMove",
    nonlethal: "EXITNIHILO.TraitNonlethal",
    olfactory: "EXITNIHILO.TraitOlfactory",
    plant: "EXITNIHILO.TraitPlant",
    poison: "EXITNIHILO.TraitPoison",
    polymorph: "EXITNIHILO.TraitPolymorph",
    possession: "EXITNIHILO.TraitPossession",
    prediction: "EXITNIHILO.TraitPrediction",
    psyche: "EXITNIHILO.TraitPsyche",
    revelation: "EXITNIHILO.TraitRevelation",
    scrying: "EXITNIHILO.TraitScrying",
    shadow: "EXITNIHILO.TraitShadow",
    sleep: "EXITNIHILO.TraitSleep",
    stance: "EXITNIHILO.TraitStance",
    summoned: "EXITNIHILO.TraitSummoned",
    teleportation: "EXITNIHILO.TraitTeleportation",
    "true-name": "EXITNIHILO.TraitTrueName",
    visual: "EXITNIHILO.TraitVisual",
};

const damageTraits = {
    ...elementalTraits,
    ...energyDamageTypes,
    light: "EXITNIHILO.TraitLight",
    magical: "EXITNIHILO.TraitMagical",
    mental: "EXITNIHILO.TraitMental",
    nonlethal: "EXITNIHILO.TraitNonlethal",
    plant: "EXITNIHILO.TraitPlant",
    radiation: "EXITNIHILO.TraitRadiation",
};

const spellTraits = {
    ...damageTraits,
    ...elementalTraits,
    ...spellOtherTraits,
};

const weaponTraits = {
    ...ancestryTraits,
    ...elementalTraits,
    ...energyDamageTypes,
    alchemical: "EXITNIHILO.TraitAlchemical",
    agile: "EXITNIHILO.TraitAgile",
    artifact: "EXITNIHILO.TraitArtifact",
    attached: "EXITNIHILO.TraitAttached",
    "attached-to-shield": "EXITNIHILO.TraitAttachedToShield",
    "attached-to-crossbow-or-firearm": "EXITNIHILO.TraitAttachedToCrossbowOrFirearm",
    auditory: "EXITNIHILO.TraitAuditory",
    backstabber: "EXITNIHILO.TraitBackstabber",
    backswing: "EXITNIHILO.TraitBackswing",
    bomb: "EXITNIHILO.TraitBomb",
    brutal: "EXITNIHILO.TraitBrutal",
    "capacity-3": "EXITNIHILO.TraitCapacity3",
    "capacity-4": "EXITNIHILO.TraitCapacity4",
    "capacity-5": "EXITNIHILO.TraitCapacity5",
    climbing: "EXITNIHILO.TraitClimbing",
    clockwork: "EXITNIHILO.TraitClockwork",
    cobbled: "EXITNIHILO.TraitCobbled",
    combination: "EXITNIHILO.TraitCombination",
    concealable: "EXITNIHILO.TraitConcealable",
    concussive: "EXITNIHILO.TraitConcussive",
    consumable: "EXITNIHILO.TraitConsumable",
    "critical-fusion": "EXITNIHILO.TraitCriticalFusion",
    cursed: "EXITNIHILO.TraitCursed",
    "deadly-d6": "EXITNIHILO.TraitDeadlyD6",
    "deadly-d8": "EXITNIHILO.TraitDeadlyD8",
    "deadly-2d8": "EXITNIHILO.TraitDeadly2D8",
    "deadly-3d8": "EXITNIHILO.TraitDeadly3D8",
    "deadly-4d8": "EXITNIHILO.TraitDeadly4D8",
    "deadly-d10": "EXITNIHILO.TraitDeadlyD10",
    "deadly-2d10": "EXITNIHILO.TraitDeadly2D10",
    "deadly-3d10": "EXITNIHILO.TraitDeadly3D10",
    "deadly-4d10": "EXITNIHILO.TraitDeadly4D10",
    "deadly-d12": "EXITNIHILO.TraitDeadlyD12",
    "deadly-2d12": "EXITNIHILO.TraitDeadly2D12",
    "deadly-3d12": "EXITNIHILO.TraitDeadly3D12",
    "deadly-4d12": "EXITNIHILO.TraitDeadly4D12",
    death: "EXITNIHILO.TraitDeath",
    disarm: "EXITNIHILO.TraitDisarm",
    disease: "EXITNIHILO.TraitDisease",
    "double-barrel": "EXITNIHILO.TraitDoubleBarrel",
    emotion: "EXITNIHILO.TraitEmotion",
    "fatal-aim-d10": "EXITNIHILO.TraitFatalAimD10",
    "fatal-aim-d12": "EXITNIHILO.TraitFatalAimD12",
    "fatal-d8": "EXITNIHILO.TraitFatalD8",
    "fatal-d10": "EXITNIHILO.TraitFatalD10",
    "fatal-d12": "EXITNIHILO.TraitFatalD12",
    fear: "EXITNIHILO.TraitFear",
    finesse: "EXITNIHILO.TraitFinesse",
    forceful: "EXITNIHILO.TraitForceful",
    fortune: "EXITNIHILO.TraitFortune",
    "free-hand": "EXITNIHILO.TraitFreeHand",
    fungus: "EXITNIHILO.TraitFungus",
    grapple: "EXITNIHILO.TraitGrapple",
    hampering: "EXITNIHILO.TraitHampering",
    healing: "EXITNIHILO.TraitHealing",
    infused: "EXITNIHILO.TraitInfused",
    inhaled: "EXITNIHILO.TraitInhaled",
    injection: "EXITNIHILO.TraitInjection",
    intelligent: "EXITNIHILO.TraitIntelligent",
    invested: "EXITNIHILO.TraitInvested",
    "jousting-d6": "EXITNIHILO.TraitJoustingD6",
    kickback: "EXITNIHILO.TraitKickback",
    light: "EXITNIHILO.TraitLight",
    magical: "EXITNIHILO.TraitMagical",
    mental: "EXITNIHILO.TraitMental",
    modular: "EXITNIHILO.TraitModular",
    monk: "EXITNIHILO.TraitMonk",
    nonlethal: "EXITNIHILO.TraitNonlethal",
    olfactory: "EXITNIHILO.TraitOlfactory",
    parry: "EXITNIHILO.TraitParry",
    plant: "EXITNIHILO.TraitPlant",
    poison: "EXITNIHILO.TraitPoison",
    propulsive: "EXITNIHILO.TraitPropulsive",
    "ranged-trip": "EXITNIHILO.TraitRangedTrip",
    reach: "EXITNIHILO.TraitReach",
    repeating: "EXITNIHILO.TraitRepeating",
    resonant: "EXITNIHILO.TraitResonant",
    saggorak: "EXITNIHILO.TraitSaggorak",
    "scatter-5": "EXITNIHILO.TraitScatter5",
    "scatter-10": "EXITNIHILO.TraitScatter10",
    "scatter-15": "EXITNIHILO.TraitScatter15",
    shadow: "EXITNIHILO.TraitShadow",
    shove: "EXITNIHILO.TraitShove",
    splash: "EXITNIHILO.TraitSplash",
    staff: "EXITNIHILO.TraitStaff",
    sweep: "EXITNIHILO.TraitSweep",
    tech: "EXITNIHILO.TraitTech",
    teleportation: "EXITNIHILO.TraitTeleportation",
    tethered: "EXITNIHILO.TraitTethered",
    thrown: "EXITNIHILO.TraitThrown",
    "thrown-10": "EXITNIHILO.TraitThrown10",
    "thrown-15": "EXITNIHILO.TraitThrown15",
    "thrown-20": "EXITNIHILO.TraitThrown20",
    "thrown-30": "EXITNIHILO.TraitThrown30",
    "thrown-40": "EXITNIHILO.TraitThrown40",
    "thrown-60": "EXITNIHILO.TraitThrown60",
    "thrown-80": "EXITNIHILO.TraitThrown80",
    "thrown-100": "EXITNIHILO.TraitThrown100",
    "thrown-200": "EXITNIHILO.TraitThrown200",
    trip: "EXITNIHILO.TraitTrip",
    twin: "EXITNIHILO.TraitTwin",
    "two-hand-d6": "EXITNIHILO.TraitTwoHandD6",
    "two-hand-d8": "EXITNIHILO.TraitTwoHandD8",
    "two-hand-d10": "EXITNIHILO.TraitTwoHandD10",
    "two-hand-d12": "EXITNIHILO.TraitTwoHandD12",
    unarmed: "EXITNIHILO.TraitUnarmed",
    "versatile-acid": "EXITNIHILO.TraitVersatileAcid",
    "versatile-b": "EXITNIHILO.TraitVersatileB",
    "versatile-chaotic": "EXITNIHILO.TraitVersatileChaotic",
    "versatile-cold": "EXITNIHILO.TraitVersatileCold",
    "versatile-electricity": "EXITNIHILO.TraitVersatileElectricity",
    "versatile-evil": "EXITNIHILO.TraitVersatileEvil",
    "versatile-fire": "EXITNIHILO.TraitVersatileFire",
    "versatile-force": "EXITNIHILO.TraitVersatileForce",
    "versatile-good": "EXITNIHILO.TraitVersatileGood",
    "versatile-lawful": "EXITNIHILO.TraitVersatileLawful",
    "versatile-negative": "EXITNIHILO.TraitVersatileNegative",
    "versatile-p": "EXITNIHILO.TraitVersatileP",
    "versatile-positive": "EXITNIHILO.TraitVersatilePositive",
    "versatile-s": "EXITNIHILO.TraitVersatileS",
    "versatile-sonic": "EXITNIHILO.TraitVersatileSonic",
    "volley-20": "EXITNIHILO.TraitVolley20",
    "volley-30": "EXITNIHILO.TraitVolley30",
    "volley-50": "EXITNIHILO.TraitVolley50"
}

const npcAttackTraits = {
    curse: "EXITNIHILO.TraitCurse",
    "reach-0": "EXITNIHILO.TraitReach0",
    "reach-10": "EXITNIHILO.TraitReach10",
    "reach-15": "EXITNIHILO.TraitReach15",
    "reach-20": "EXITNIHILO.TraitReach20",
    "reach-25": "EXITNIHILO.TraitReach25",
    "reach-30": "EXITNIHILO.TraitReach30",
    "reach-40": "EXITNIHILO.TraitReach40",
    "reach-50": "EXITNIHILO.TraitReach50",
    "reach-60": "EXITNIHILO.TraitReach60",
    "reach-100": "EXITNIHILO.TraitReach100",
    "reach-1000": "EXITNIHILO.TraitReach1000",
    "reload-0": "EXITNIHILO.TraitReload0",
    "reload-1": "EXITNIHILO.TraitReload1",
    "reload-2": "EXITNIHILO.TraitReload2",
    "reload-1-min": "EXITNIHILO.TraitReload1Min",
};

const featTraits = {
    ...ancestryTraits,
    ...damageTraits,
    ...spellTraits,
    additive1: "EXITNIHILO.TraitAdditive1",
    additive2: "EXITNIHILO.TraitAdditive2",
    additive3: "EXITNIHILO.TraitAdditive3",
    aftermath: "EXITNIHILO.TraitAftermath",
    alchemical: "EXITNIHILO.TraitAlchemical",
    archetype: "EXITNIHILO.TraitArchetype",
    auditory: "EXITNIHILO.TraitAuditory",
    aura: "EXITNIHILO.TraitAura",
    class: "EXITNIHILO.Class",
    concentrate: "EXITNIHILO.TraitConcentrate",
    dedication: "EXITNIHILO.TraitDedication",
    detection: "EXITNIHILO.TraitDetection",
    deviant: "EXITNIHILO.TraitDeviant",
    downtime: "EXITNIHILO.TraitDowntime",
    emotion: "EXITNIHILO.TraitEmotion",
    evolution: "EXITNIHILO.TraitEvolution",
    esoterica: "EXITNIHILO.TraitEsoterica",
    exploration: "EXITNIHILO.TraitExploration",
    fear: "EXITNIHILO.TraitFear",
    finisher: "EXITNIHILO.TraitFinisher",
    flourish: "EXITNIHILO.TraitFlourish",
    fortune: "EXITNIHILO.TraitFortune",
    general: "EXITNIHILO.TraitGeneral",
    injury: "EXITNIHILO.TraitInjury",
    lineage: "EXITNIHILO.TraitLineage",
    manipulate: "EXITNIHILO.TraitManipulate",
    metamagic: "EXITNIHILO.TraitMetamagic",
    mindshift: "EXITNIHILO.TraitMindshift",
    modification: "EXITNIHILO.TraitModification",
    move: "EXITNIHILO.TraitMove",
    multiclass: "EXITNIHILO.TraitMulticlass",
    oath: "EXITNIHILO.TraitOath",
    olfactory: "EXITNIHILO.TraitOlfactory",
    open: "EXITNIHILO.TraitOpen",
    "pervasive-magic": "EXITNIHILO.TraitPervasiveMagic",
    poison: "EXITNIHILO.TraitPoison",
    press: "EXITNIHILO.TraitPress",
    rage: "EXITNIHILO.TraitRage",
    reckless: "EXITNIHILO.TraitReckless",
    reflection: "EXITNIHILO.TraitReflection",
    secret: "EXITNIHILO.TraitSecret",
    skill: "EXITNIHILO.TraitSkill",
    social: "EXITNIHILO.TraitSocial",
    spellshot: "EXITNIHILO.TraitSpellshot",
    stamina: "EXITNIHILO.TraitStamina",
    stance: "EXITNIHILO.TraitStance",
    tandem: "EXITNIHILO.TraitTandem",
    time: "EXITNIHILO.TraitTime",
    "true-name": "EXITNIHILO.TraitTrueName",
    unstable: "EXITNIHILO.TraitUnstable",
    vigilante: "EXITNIHILO.TraitVigilante",
    virulent: "EXITNIHILO.TraitVirulent",
};

const consumableTraits = {
    ...damageTraits,
    ...elementalTraits,
    additive1: "EXITNIHILO.TraitAdditive1",
    additive2: "EXITNIHILO.TraitAdditive2",
    additive3: "EXITNIHILO.TraitAdditive3",
    alchemical: "EXITNIHILO.TraitAlchemical",
    auditory: "EXITNIHILO.TraitAuditory",
    aura: "EXITNIHILO.TraitAura",
    catalyst: "EXITNIHILO.TraitCatalyst",
    clockwork: "EXITNIHILO.TraitClockwork",
    consumable: "EXITNIHILO.TraitConsumable",
    contact: "EXITNIHILO.TraitContact",
    cursed: "EXITNIHILO.TraitCursed",
    drug: "EXITNIHILO.TraitDrug",
    elixir: "EXITNIHILO.TraitElixir",
    emotion: "EXITNIHILO.TraitEmotion",
    fear: "EXITNIHILO.TraitFear",
    fey: "EXITNIHILO.TraitFey",
    fortune: "EXITNIHILO.TraitFortune",
    fulu: "EXITNIHILO.TraitFulu",
    gadget: "EXITNIHILO.TraitGadget",
    healing: "EXITNIHILO.TraitHealing",
    incapacitation: "EXITNIHILO.TraitIncapacitation",
    infused: "EXITNIHILO.TraitInfused",
    ingested: "EXITNIHILO.TraitIngested",
    inhaled: "EXITNIHILO.TraitInhaled",
    injury: "EXITNIHILO.TraitInjury",
    kobold: "EXITNIHILO.TraitKobold",
    light: "EXITNIHILO.TraitLight",
    magical: "EXITNIHILO.TraitMagical",
    mechanical: "EXITNIHILO.TraitMechanical",
    misfortune: "EXITNIHILO.TraitMisfortune",
    morph: "EXITNIHILO.TraitMorph",
    mutagen: "EXITNIHILO.TraitMutagen",
    oil: "EXITNIHILO.TraitOil",
    olfactory: "EXITNIHILO.TraitOlfactory",
    poison: "EXITNIHILO.TraitPoison",
    polymorph: "EXITNIHILO.TraitPolymorph",
    potion: "EXITNIHILO.TraitPotion",
    precious: "EXITNIHILO.TraitPrecious",
    scroll: "EXITNIHILO.TraitScroll",
    scrying: "EXITNIHILO.TraitScrying",
    sleep: "EXITNIHILO.TraitSleep",
    snare: "EXITNIHILO.TraitSnare",
    splash: "EXITNIHILO.TraitSplash",
    structure: "EXITNIHILO.TraitStructure",
    talisman: "EXITNIHILO.TraitTalisman",
    teleportation: "EXITNIHILO.TraitTeleportation",
    trap: "EXITNIHILO.TraitTrap",
    virulent: "EXITNIHILO.TraitVirulent",
    visual: "EXITNIHILO.TraitVisual",
    wand: "EXITNIHILO.TraitWand",
};

const actionTraits = {
    ...featTraits,
    ...consumableTraits,
    ...spellTraits,
    circus: "EXITNIHILO.TraitCircus",
    summon: "EXITNIHILO.TraitSummon",
};

const hazardTraits = {
    ...damageTraits,
    alchemical: "EXITNIHILO.TraitAlchemical",
    aquatic: "EXITNIHILO.TraitAquatic",
    auditory: "EXITNIHILO.TraitAuditory",
    clockwork: "EXITNIHILO.TraitClockwork",
    consumable: "EXITNIHILO.TraitConsumable",
    curse: "EXITNIHILO.TraitCurse",
    environmental: "EXITNIHILO.TraitEnvironmental",
    fungus: "EXITNIHILO.TraitFungus",
    haunt: "EXITNIHILO.TraitHaunt",
    inhaled: "EXITNIHILO.TraitInhaled",
    kaiju: "EXITNIHILO.TraitKaiju",
    magical: "EXITNIHILO.TraitMagical",
    mechanical: "EXITNIHILO.TraitMechanical",
    poison: "EXITNIHILO.TraitPoison",
    steam: "EXITNIHILO.TraitSteam",
    summoned: "EXITNIHILO.TraitSummoned",
    technological: "EXITNIHILO.TraitTechnological",
    teleportation: "EXITNIHILO.TraitTeleportation",
    trap: "EXITNIHILO.TraitTrap",
    virulent: "EXITNIHILO.TraitVirulent",
    visual: "EXITNIHILO.TraitVisual",
};

const vehicleTraits = {
    artifact: "EXITNIHILO.TraitArtifact",
    clockwork: "EXITNIHILO.TraitClockwork",
    magical: "EXITNIHILO.TraitMagical",
    teleportation: "EXITNIHILO.TraitTeleportation",
};

const equipmentTraits = {
    ...ancestryTraits,
    ...elementalTraits,
    ...energyDamageTypes,
    adjustment: "EXITNIHILO.TraitAdjustment",
    alchemical: "EXITNIHILO.TraitAlchemical",
    apex: "EXITNIHILO.TraitApex",
    artifact: "EXITNIHILO.TraitArtifact",
    auditory: "EXITNIHILO.TraitAuditory",
    aura: "EXITNIHILO.TraitAura",
    clockwork: "EXITNIHILO.TraitClockwork",
    companion: "EXITNIHILO.TraitCompanion",
    contract: "EXITNIHILO.TraitContract",
    consecration: "EXITNIHILO.TraitConsecration",
    cursed: "EXITNIHILO.TraitCursed",
    darkness: "EXITNIHILO.TraitDarkness",
    death: "EXITNIHILO.TraitDeath",
    detection: "EXITNIHILO.TraitDetection",
    eidolon: "EXITNIHILO.TraitEidolon",
    emotion: "EXITNIHILO.TraitEmotion",
    extradimensional: "EXITNIHILO.TraitExtradimensional",
    fear: "EXITNIHILO.TraitFear",
    focused: "EXITNIHILO.TraitFocused",
    fortune: "EXITNIHILO.TraitFortune",
    fulu: "EXITNIHILO.TraitFulu",
    gadget: "EXITNIHILO.TraitGadget",
    grimoire: "EXITNIHILO.TraitGrimoire",
    healing: "EXITNIHILO.TraitHealing",
    infused: "EXITNIHILO.TraitInfused",
    intelligent: "EXITNIHILO.TraitIntelligent",
    invested: "EXITNIHILO.TraitInvested",
    light: "EXITNIHILO.TraitLight",
    magical: "EXITNIHILO.TraitMagical",
    mental: "EXITNIHILO.TraitMental",
    misfortune: "EXITNIHILO.TraitMisfortune",
    mounted: "EXITNIHILO.TraitMounted",
    nonlethal: "EXITNIHILO.TraitNonlethal",
    plant: "EXITNIHILO.TraitPlant",
    poison: "EXITNIHILO.TraitPoison",
    portable: "EXITNIHILO.TraitPortable",
    precious: "EXITNIHILO.TraitPrecious",
    revelation: "EXITNIHILO.TraitRevelation",
    saggorak: "EXITNIHILO.TraitSaggorak",
    scrying: "EXITNIHILO.TraitScrying",
    sleep: "EXITNIHILO.TraitSleep",
    spellheart: "EXITNIHILO.TraitSpellheart",
    staff: "EXITNIHILO.TraitStaff",
    steam: "EXITNIHILO.TraitSteam",
    structure: "EXITNIHILO.TraitStructure",
    tattoo: "EXITNIHILO.TraitTattoo",
    teleportation: "EXITNIHILO.TraitTeleportation",
    visual: "EXITNIHILO.TraitVisual",
    wand: "EXITNIHILO.TraitWand",
};

const armorTraits = {
    ...elementalTraits,
    apex: "EXITNIHILO.TraitApex",
    artifact: "EXITNIHILO.TraitArtifact",
    auditory: "EXITNIHILO.TraitAuditory",
    bulwark: "EXITNIHILO.TraitBulwark",
    clockwork: "EXITNIHILO.TraitClockwork",
    comfort: "EXITNIHILO.TraitComfort",
    cursed: "EXITNIHILO.TraitCursed",
    extradimensional: "EXITNIHILO.TraitExtradimensional",
    focused: "EXITNIHILO.TraitFocused",
    force: "EXITNIHILO.TraitForce",
    flexible: "EXITNIHILO.TraitFlexible",
    intelligent: "EXITNIHILO.TraitIntelligent",
    invested: "EXITNIHILO.TraitInvested",
    light: "EXITNIHILO.TraitLight",
    magical: "EXITNIHILO.TraitMagical",
    noisy: "EXITNIHILO.TraitNoisy",
};

export {
    actionTraits,
    ancestryItemTraits,
    ancestryTraits,
    armorTraits,
    consumableTraits,
    creatureTraits,
    damageTraits,
    elementalTraits,
    energyDamageTypes,
    equipmentTraits,
    featTraits,
    hazardTraits,
    npcAttackTraits,
    spellTraits,
    vehicleTraits,
    weaponTraits,
};
