export const ATTRIBUTE_ABBREVIATIONS = new Set(["phy", "adr", "int", "psy", "soc"] as const);

export const CREATURE_ACTOR_TYPES = ["character", "npc"] as const;

export const SKILL_ABBREVIATIONS = new Set([
    "arg",
    "art",
    "ath",
    "bar",
    "bri",
    "che",
    "cui",
    "dis",
    "equ",
    "esq",
    "fil",
    "jar",
    "lan",
    "nag",
    "per",
    "psy",
    "sec",
    "sur",
    "tec",
] as const);

export const SKILL_DICTIONARY = {
    arg: "argumenter",
    art: "arts",
    ath: "athletisme",
    bar: "baratin",
    bri: "bricolage",
    che: "chercher",
    cui: "cuisine",
    dis: "discretion",
    equ: "equitation",
    esq: "esquive",
    fil: "filouterie",
    jar: "jardinage",
    lan: "langues",
    nag: "nager",
    per: "perception",
    psy: "psychologie",
    sec: "secourisme",
    sur: "survie",
    tec: "technologie",
} as const;

export const COMPETENCES = [
    "argumenter",
    "art1",
    "art2",
    "athletisme",
    "baratin",
    "bricolage",
    "chercher",
    "cuisine",
    "jardinage",
    "discretion",
    "equitation",
    "esquive",
    "langues",
    "filouterie",
    "nager",
    "perception",
    "pilotage1",
    "pilotage2",
    "secourisme",
    "profession1",
    "profession2",
    "psychologie",
    "survie",
    "technologie",
    "corpsACorps",
    "corpsACorpsArme",
    "armeAProjectile",
    "armeDePoing",
    "fusil",
    "fusilDAssaut",
    "fusilDePrecision",
    "explosif",
];

export const COMPETENCES_ENFANCE = [
    "art1",
    "athletisme",
    "baratin",
    "jardinage",
    "equitation",
    "esquive",
    "langues",
    "nager",
    "perception",
    "survie",
] as const;

export const COMPETENCES_ADOLESCENCE = [
    "art1",
    "art2",
    "athletisme",
    "baratin",
    "bricolage",
    "chercher",
    "cuisine",
    "jardinage",
    "discretion",
    "equitation",
    "esquive",
    "langues",
    "filouterie",
    "nager",
    "perception",
    "pilotage1",
    "secourisme",
    "survie",
    "technologie",
    "corpsACorps",
    "corpsACorpsArme",
    "armeAProjectile",
    "fusil",
] as const;

export const COMPETENCES_ADULTE = [
    "argumenter",
    "art1",
    "art2",
    "athletisme",
    "baratin",
    "bricolage",
    "chercher",
    "cuisine",
    "jardinage",
    "discretion",
    "equitation",
    "esquive",
    "langues",
    "filouterie",
    "nager",
    "perception",
    "pilotage1",
    "pilotage2",
    "secourisme",
    "profession1",
    "profession2",
    "psychologie",
    "survie",
    "technologie",
    "corpsACorps",
    "corpsACorpsArme",
    "armeAProjectile",
    "fusil",
    "armeDePoing",
    "fusilDAssaut",
    "fusilDePrecision",
    "explosif",
] as const;

export const SKILL_LONG_FORMS = new Set(Object.values(SKILL_DICTIONARY));
